-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.16-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table bte.bestbuy_category
CREATE TABLE IF NOT EXISTS `bestbuy_category` (
  `category_id` varchar(20) NOT NULL,
  `parent_id` varchar(20) NOT NULL,
  `category_name` varchar(80) NOT NULL,
  `category_desc` varchar(200) NOT NULL,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table bte.bestbuy_category: ~0 rows (approximately)
/*!40000 ALTER TABLE `bestbuy_category` DISABLE KEYS */;
INSERT IGNORE INTO `bestbuy_category` (`category_id`, `parent_id`, `category_name`, `category_desc`) VALUES
	('CAT_10007', 'CAT_659225', 'Metal Detectors', 'Toys, Sports & Recreation > Sports & Recreation > Metal Detectors'),
	('CAT_10011', 'CAT_22210', 'Art & Wall Décor', 'Home Decor - Category Branch > Art & Wall Décor'),
	('CAT_10015', 'CAT_11', 'Speaker Stands and Mounts', 'Home Theatre > Speaker Stands and Mounts'),
	('CAT_1002', 'CAT_30658', 'Laptops', 'Computers > Laptops'),
	('CAT_1003', 'CAT_30658', 'Desktop Computers', 'Computers > Desktop Computers'),
	('CAT_1006', 'CAT_30658', 'Monitors', 'Computers > Monitors'),
	('CAT_10086', 'CAT_19', 'MP3 CD Players', 'iPod & Portable Audio > MP3 CD Players'),
	('CAT_10088', 'CAT_19', 'Portable Radios', 'iPod & Portable Audio > Portable Radios'),
	('CAT_10089', 'CAT_31177', 'Digital Voice Recorders', 'Office Supplies > Digital Voice Recorders'),
	('CAT_1012', 'CAT_30658', 'Scanners', 'Computers > Scanners'),
	('CAT_1021', 'CAT_31177', 'Batteries', 'Office Supplies > Batteries'),
	('CAT_10233', 'CAT_30658', 'Single Function Laser Printers', 'Computers > Single Function Laser Printers'),
	('CAT_1024', 'CAT_11', 'Home Theatre Cables & Accessories', 'Home Theatre > Home Theatre Cables & Accessories'),
	('CAT_1026', 'CAT_11', 'Home Theatre Systems', 'Home Theatre > Home Theatre Systems'),
	('CAT_1034', 'CAT_15', 'PC Games', 'Gaming > PC Games'),
	('CAT_1042', 'CAT_11', 'DVD Players - Category Branch - to be deleted', 'Home Theatre > DVD Players - Category Branch - to be deleted'),
	('CAT_10446', 'CAT_30658', 'Surge Protectors', 'Computers > Surge Protectors'),
	('CAT_1047', 'CAT_11', 'Home Speakers - Category Branch', 'Home Theatre > Home Speakers - Category Branch'),
	('CAT_10476', 'CAT_30658', 'Computer Cases', 'Computers > Computer Cases'),
	('CAT_10481', 'CAT_30658', 'Motherboards', 'Computers > Motherboards'),
	('CAT_10482', 'CAT_30658', 'Power Supplies', 'Computers > Power Supplies'),
	('CAT_10483', 'CAT_30658', 'Processors', 'Computers > Processors'),
	('CAT_10488', 'CAT_30658', 'Wired Hubs & Switches', 'Computers > Wired Hubs & Switches'),
	('CAT_10489', 'CAT_30658', 'Wired Modems', 'Computers > Wired Modems'),
	('CAT_10492', 'CAT_30658', 'Single Function Inkjet Printers', 'Computers > Single Function Inkjet Printers'),
	('CAT_10494', 'CAT_30658', 'Network Cables', 'Computers > Network Cables'),
	('CAT_10495', 'CAT_30658', 'Wired Routers', 'Computers > Wired Routers'),
	('CAT_10499', 'CAT_30658', 'Sound Cards', 'Computers > Sound Cards'),
	('CAT_10526', 'CAT_30658', 'Video Capture & Editing', 'Computers > Video Capture & Editing'),
	('CAT_10546', 'CAT_19', 'CD Players', 'iPod & Portable Audio > CD Players'),
	('CAT_10551', 'CAT_11', 'Home Theatre Receivers', 'Home Theatre > Home Theatre Receivers'),
	('CAT_10554', 'CAT_1047', 'Subwoofers', 'Home Theatre > Home Speakers - Category Branch > Subwoofers'),
	('CAT_10561', 'CAT_1042', 'DVD Players - to be deleted', 'Home Theatre > DVD Players - Category Branch - to be deleted > DVD Players - to be deleted'),
	('CAT_10566', 'CAT_31177', 'Answering Machines', 'Office Supplies > Answering Machines'),
	('CAT_10568', 'CAT_1042', 'Portable DVD Players - to be deleted', 'Home Theatre > DVD Players - Category Branch - to be deleted > Portable DVD Players - to be deleted'),
	('CAT_10573', 'CAT_11', 'Stereo Receivers', 'Home Theatre > Stereo Receivers'),
	('CAT_10735', 'CAT_27115', 'Wall Ovens', 'Appliances > Wall Ovens'),
	('CAT_10737', 'CAT_28839', 'Pants & Shorts', 'Tools & Garden > Workwear & Apparel - Category Branch > Pants & Shorts'),
	('CAT_10738', 'CAT_28839', 'Socks', 'Tools & Garden > Workwear & Apparel - Category Branch > Socks'),
	('CAT_10742', 'CAT_27115', 'Stacked Laundry Pairs', 'Appliances > Stacked Laundry Pairs'),
	('CAT_10744', 'CAT_27115', 'Gas Ranges', 'Appliances > Gas Ranges'),
	('CAT_1076', 'CAT_30658', 'Computer Memory', 'Computers > Computer Memory'),
	('CAT_10776', 'CAT_30658', 'Fax Machines', 'Computers > Fax Machines'),
	('CAT_10781', 'CAT_30658', 'All-in-One Inkjet Printers', 'Computers > All-in-One Inkjet Printers'),
	('CAT_1082', 'CAT_30658', 'DVD Drives - Category Branch', 'Computers > DVD Drives - Category Branch'),
	('CAT_10831', 'CAT_27115', 'Humidifiers', 'Appliances > Humidifiers'),
	('CAT_10832', 'CAT_27115', 'Dehumidifiers', 'Appliances > Dehumidifiers'),
	('CAT_10837', 'CAT_27115', 'Air Purifiers', 'Appliances > Air Purifiers'),
	('CAT_1084', 'CAT_30658', 'Hard Drives', 'Computers > Hard Drives'),
	('CAT_10842', 'CAT_27115', 'Toasters', 'Appliances > Toasters'),
	('CAT_10843', 'CAT_27115', 'Toaster Ovens', 'Appliances > Toaster Ovens'),
	('CAT_10844', 'CAT_27115', 'Food Processor & Choppers', 'Appliances > Food Processor & Choppers'),
	('CAT_10845', 'CAT_27115', 'Cookers & Steamers', 'Appliances > Cookers & Steamers'),
	('CAT_10848', 'CAT_27115', 'Deep Fryers', 'Appliances > Deep Fryers'),
	('CAT_10851', 'CAT_27115', 'Bread Makers', 'Appliances > Bread Makers'),
	('CAT_10852', 'CAT_27115', 'Indoor Grills', 'Appliances > Indoor Grills'),
	('CAT_10857', 'CAT_27316', 'Can Openers', 'Kitchen Gadgets & Utensils - Category Branch > Can Openers'),
	('CAT_10858', 'CAT_31437', 'Electric Knives', 'Kitchen Knives - Category Branch > Electric Knives'),
	('CAT_10859', 'CAT_27115', 'Coffee Grinders', 'Appliances > Coffee Grinders'),
	('CAT_10860', 'CAT_27115', 'Water Purifiers & Coolers', 'Appliances > Water Purifiers & Coolers'),
	('CAT_10861', 'CAT_27115', 'Popcorn Makers', 'Appliances > Popcorn Makers'),
	('CAT_10872', 'CAT_27115', 'Electric & Gas Cooktops', 'Appliances > Electric & Gas Cooktops'),
	('CAT_11', '', 'Home Theatre', 'Home Theatre'),
	('CAT_11008', 'CAT_22210', 'Fireplaces', 'Home Decor - Category Branch > Fireplaces'),
	('CAT_1101', 'CAT_9', 'Car Decks - Single DIN', 'Car, Marine & GPS > Car Decks - Single DIN'),
	('CAT_11031', 'CAT_9', 'Car Amplifiers - 1 & 2 Channels', 'Car, Marine & GPS > Car Amplifiers - 1 & 2 Channels'),
	('CAT_11032', 'CAT_9', 'Car Amplifiers - 4+ Channels', 'Car, Marine & GPS > Car Amplifiers - 4+ Channels'),
	('CAT_11035', 'CAT_9', 'Car Equalizers & Crossovers', 'Car, Marine & GPS > Car Equalizers & Crossovers'),
	('CAT_1104', 'CAT_9', 'Car Speakers', 'Car, Marine & GPS > Car Speakers'),
	('CAT_1105', 'CAT_9', 'Car Subwoofers', 'Car, Marine & GPS > Car Subwoofers'),
	('CAT_11062', 'CAT_9', 'Car Subwoofer Enclosures', 'Car, Marine & GPS > Car Subwoofer Enclosures'),
	('CAT_1111', 'CAT_31177', 'Calculators', 'Office Supplies > Calculators'),
	('CAT_11111', 'CAT_26336', 'Cellular Batteries', 'Cellular Phones > Cellular Batteries'),
	('CAT_1127', 'CAT_14', 'Compact Digital Cameras', 'Cameras & Camcorders > Compact Digital Cameras'),
	('CAT_11288', 'CAT_30658', 'USB & FireWire Cards & Hubs', 'Computers > USB & FireWire Cards & Hubs'),
	('CAT_1159937', 'CAT_30837', 'Crib Bedding & Accessories', 'Baby & Kids > Crib Bedding & Accessories'),
	('CAT_1159939', 'CAT_30837', 'Baby & Child Fashion Accessories', 'Baby & Kids > Baby & Child Fashion Accessories'),
	('CAT_1159940', 'CAT_30837', 'Nursery Decor', 'Baby & Kids > Nursery Decor'),
	('CAT_1159945', 'CAT_30837', 'Baby Proofing & Safe Sleeping', 'Baby & Kids > Baby Proofing & Safe Sleeping'),
	('CAT_1170746', 'CAT_654823', 'Virtual Reality Headsets', 'Wearable Technology > Virtual Reality Headsets'),
	('CAT_1171', 'CAT_655410', 'Ink & Toner Cartridges', 'Computers > Ink & Toner - Category Branch > Ink & Toner Cartridges'),
	('CAT_12036', 'CAT_9', 'Car Multimedia Packages', 'Car, Marine & GPS > Car Multimedia Packages'),
	('CAT_12037', 'CAT_9', 'Car GPS Navigation Modules', 'Car, Marine & GPS > Car GPS Navigation Modules'),
	('CAT_12038', 'CAT_9', 'Car Decks - Double DIN', 'Car, Marine & GPS > Car Decks - Double DIN'),
	('CAT_12039', 'CAT_9', 'Car Video Monitors', 'Car, Marine & GPS > Car Video Monitors'),
	('CAT_1295098', '', 'Bed Sheets', 'Bed Sheets'),
	('CAT_13', '', 'Movies', 'Movies'),
	('CAT_14', '', 'Cameras & Camcorders', 'Cameras & Camcorders'),
	('CAT_14262', 'CAT_30658', 'Gamepads, Joysticks & Aviation Controls (for PC only)', 'Computers > Gamepads, Joysticks & Aviation Controls (for PC only)'),
	('CAT_14263', 'CAT_30658', 'Joysticks & Aviation Controls (for PC only)', 'Computers > Joysticks & Aviation Controls (for PC only)'),
	('CAT_14266', 'CAT_30658', 'Keyboard and Mouse Combos', 'Computers > Keyboard and Mouse Combos'),
	('CAT_14444', 'CAT_31177', 'Labels & Tags', 'Office Supplies > Labels & Tags'),
	('CAT_14503', 'CAT_9', 'Car Security & Starters', 'Car, Marine & GPS > Car Security & Starters'),
	('CAT_14700', 'CAT_1047', 'Surround Speaker Packages (Speakers & Subwoofer Only)', 'Home Theatre > Home Speakers - Category Branch > Surround Speaker Packages (Speakers & Subwoofer Only)'),
	('CAT_15', '', 'Gaming', 'Gaming'),
	('CAT_1544', 'CAT_30658', 'Projectors', 'Computers > Projectors'),
	('CAT_16', '', 'Music', 'Music'),
	('CAT_1653054', 'CAT_30840', 'Luggage & Bags Temp - Category Branch', 'Health, Beauty & Travel > Luggage & Bags Temp - Category Branch'),
	('CAT_17', '', 'Gift Cards', 'Gift Cards'),
	('CAT_17131', 'CAT_27115', 'Bar Fridges', 'Appliances > Bar Fridges'),
	('CAT_1810', 'CAT_27115', 'Canister & Upright Vacuums', 'Appliances > Canister & Upright Vacuums'),
	('CAT_19', '', 'iPod & Portable Audio', 'iPod & Portable Audio'),
	('CAT_1949', 'CAT_27115', 'Washers', 'Appliances > Washers'),
	('CAT_1950', 'CAT_27115', 'Dryers', 'Appliances > Dryers'),
	('CAT_1951', 'CAT_27115', 'Dishwashers', 'Appliances > Dishwashers'),
	('CAT_1952', 'CAT_27115', 'Electric Ranges', 'Appliances > Electric Ranges'),
	('CAT_1953', 'CAT_27115', 'Refrigerators', 'Appliances > Refrigerators'),
	('CAT_1954', 'CAT_27115', 'Freezers', 'Appliances > Freezers'),
	('CAT_19542', 'CAT_27115', 'Appliances Accessories', 'Appliances > Appliances Accessories'),
	('CAT_19561', 'CAT_27115', 'Range Hoods', 'Appliances > Range Hoods'),
	('CAT_19994', 'CAT_30658', 'Wireless Routers', 'Computers > Wireless Routers'),
	('CAT_19996', 'CAT_30658', 'Print Servers', 'Computers > Print Servers'),
	('CAT_19997', 'CAT_30658', 'Network Cards', 'Computers > Network Cards'),
	('CAT_2001', 'CAT_11', 'Satellite TV', 'Home Theatre > Satellite TV'),
	('CAT_2002', 'CAT_11', 'Digital Cable - Category Branch', 'Home Theatre > Digital Cable - Category Branch'),
	('CAT_22', '', 'Multi-Dept and Generic', 'Multi-Dept and Generic'),
	('CAT_22082', 'CAT_17', 'Gift Cards', 'Gift Cards > Gift Cards'),
	('CAT_22083', 'CAT_22082', 'Future Shop Gift Cards', 'Gift Cards > Gift Cards > Future Shop Gift Cards'),
	('CAT_22210', '', 'Home Decor - Category Branch', 'Home Decor - Category Branch'),
	('CAT_22569', 'CAT_14', 'Lens Filters', 'Cameras & Camcorders > Lens Filters'),
	('CAT_22793', 'CAT_19', 'Apple iPod & MP3 Cases', 'iPod & Portable Audio > Apple iPod & MP3 Cases'),
	('CAT_22953', 'CAT_11', 'Wireless Audio Systems', 'Home Theatre > Wireless Audio Systems'),
	('CAT_23013', 'CAT_31177', 'VoIP & Internet Phone', 'Office Supplies > VoIP & Internet Phone'),
	('CAT_23033', 'CAT_30658', 'Blank Discs, Cases & Accessories', 'Computers > Blank Discs, Cases & Accessories'),
	('CAT_23115', 'CAT_9', 'Marine Speakers', 'Car, Marine & GPS > Marine Speakers'),
	('CAT_23116', 'CAT_9', 'Marine Amplifiers', 'Car, Marine & GPS > Marine Amplifiers'),
	('CAT_23274', 'CAT_19', 'Headphones & Headsets - Category Branch', 'iPod & Portable Audio > Headphones & Headsets - Category Branch'),
	('CAT_23278', 'CAT_30658', 'Computer Battery Back Up', 'Computers > Computer Battery Back Up'),
	('CAT_23353', 'CAT_15', 'Video Games', 'Gaming > Video Games'),
	('CAT_23553', 'CAT_659225', 'Knives & Blades', 'Toys, Sports & Recreation > Sports & Recreation > Knives & Blades'),
	('CAT_23753', 'CAT_14', 'Digital Memory', 'Cameras & Camcorders > Digital Memory'),
	('CAT_23773', 'CAT_14', 'DSLR Cameras', 'Cameras & Camcorders > DSLR Cameras'),
	('CAT_23813', 'CAT_30658', 'USB Drives', 'Computers > USB Drives'),
	('CAT_23853', 'CAT_30658', 'Webcams', 'Computers > Webcams'),
	('CAT_23875', 'CAT_27115', 'Wine Cellars & Coolers', 'Appliances > Wine Cellars & Coolers'),
	('CAT_24253', 'CAT_660196', 'Outdoor Furniture Covers', 'Furniture - Category Branch > Outdoor Furniture Covers'),
	('CAT_24635', 'CAT_9', 'Replacement Remotes', 'Car, Marine & GPS > Replacement Remotes'),
	('CAT_24734', 'CAT_31177', 'DECT Cordless Phones', 'Office Supplies > DECT Cordless Phones'),
	('CAT_24853', 'CAT_9', 'Car &  Motorcycle GPS', 'Car, Marine & GPS > Car &  Motorcycle GPS'),
	('CAT_24854', 'CAT_11', 'DVD Video Recorders', 'Home Theatre > DVD Video Recorders'),
	('CAT_24913', 'CAT_659219', 'Other Toys & Gadgets', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Other Toys & Gadgets'),
	('CAT_24996', 'CAT_2002', 'Digital Cable Boxes', 'Home Theatre > Digital Cable - Category Branch > Digital Cable Boxes'),
	('CAT_25033', 'CAT_659225', 'Hammocks', 'Toys, Sports & Recreation > Sports & Recreation > Hammocks'),
	('CAT_25320', 'CAT_11', 'Blu-ray & DVD Players - Category Branch', 'Home Theatre > Blu-ray & DVD Players - Category Branch'),
	('CAT_25595', 'CAT_30658', 'Laptop Batteries', 'Computers > Laptop Batteries'),
	('CAT_25614', 'CAT_30658', 'Wireless USB Adapters', 'Computers > Wireless USB Adapters'),
	('CAT_25615', 'CAT_30658', 'TV Tuners', 'Computers > TV Tuners'),
	('CAT_25617', 'CAT_30658', 'Video Cards', 'Computers > Video Cards'),
	('CAT_25713', 'CAT_14', 'Camcorders', 'Cameras & Camcorders > Camcorders'),
	('CAT_25756', '', 'More Smart Home & Security', 'More Smart Home & Security'),
	('CAT_25794', 'CAT_14', 'Camera Lenses - Category Branch', 'Cameras & Camcorders > Camera Lenses - Category Branch'),
	('CAT_25835', 'CAT_9', 'Marine GPS', 'Car, Marine & GPS > Marine GPS'),
	('CAT_25836', 'CAT_9', 'Outdoor GPS', 'Car, Marine & GPS > Outdoor GPS'),
	('CAT_25855', 'CAT_14', 'Digital Photo Frames', 'Cameras & Camcorders > Digital Photo Frames'),
	('CAT_25876', 'CAT_27115', 'Air Purifier Filters', 'Appliances > Air Purifier Filters'),
	('CAT_25881', 'CAT_11', 'Home Audio Adapters', 'Home Theatre > Home Audio Adapters'),
	('CAT_25930', 'CAT_26336', 'iPhone Power & Cables', 'Cellular Phones > iPhone Power & Cables'),
	('CAT_25938', 'CAT_26336', 'Bluetooth Handsfree Headsets', 'Cellular Phones > Bluetooth Handsfree Headsets'),
	('CAT_25940', 'CAT_26336', 'Bluetooth Speakerphones', 'Cellular Phones > Bluetooth Speakerphones'),
	('CAT_25944', 'CAT_27383', 'Home Automation Modules', 'Home Automation & Accessories - Category Branch > Home Automation Modules'),
	('CAT_26299', 'CAT_9', 'Back Up Cameras & Dash Cams', 'Car, Marine & GPS > Back Up Cameras & Dash Cams'),
	('CAT_26336', '', 'Cellular Phones', 'Cellular Phones'),
	('CAT_26337', '', 'Toys, Sports & Recreation', 'Toys, Sports & Recreation'),
	('CAT_26355', 'CAT_11', 'Wall Mounts', 'Home Theatre > Wall Mounts'),
	('CAT_26378', 'CAT_15', 'Video Game Accessories', 'Gaming > Video Game Accessories'),
	('CAT_26379', 'CAT_659225', 'Tents, Shelters & Screen Rooms', 'Toys, Sports & Recreation > Sports & Recreation > Tents, Shelters & Screen Rooms'),
	('CAT_26380', 'CAT_30840', 'Vitamins & Supplements', 'Health, Beauty & Travel > Vitamins & Supplements'),
	('CAT_26395', 'CAT_1082', 'Blu-ray Drives', 'Computers > DVD Drives - Category Branch > Blu-ray Drives'),
	('CAT_26435', 'CAT_19', 'iPods & Portable Media Players', 'iPod & Portable Audio > iPods & Portable Media Players'),
	('CAT_26455', 'CAT_30658', 'All-in-One Laser Printers', 'Computers > All-in-One Laser Printers'),
	('CAT_26575', 'CAT_31177', 'Corded Phones', 'Office Supplies > Corded Phones'),
	('CAT_26995', 'CAT_19', 'Portable, Wireless & Compact Speaker Systems', 'iPod & Portable Audio > Portable, Wireless & Compact Speaker Systems'),
	('CAT_27000', 'CAT_31198', 'Backpacks', 'Health, Beauty & Travel > Luggage - Category Branch > Backpacks'),
	('CAT_27115', '', 'Appliances', 'Appliances'),
	('CAT_27123', 'CAT_27115', 'Juicers', 'Appliances > Juicers'),
	('CAT_27136', 'CAT_27115', 'Microwaves', 'Appliances > Microwaves'),
	('CAT_27237', '', 'Musical Instruments', 'Musical Instruments'),
	('CAT_27238', 'CAT_27237', 'Electric Guitars', 'Musical Instruments > Electric Guitars'),
	('CAT_27239', 'CAT_27237', 'Keyboards', 'Musical Instruments > Keyboards'),
	('CAT_27244', 'CAT_27237', 'Karaoke', 'Musical Instruments > Karaoke'),
	('CAT_27246', 'CAT_27237', 'Sheet Music', 'Musical Instruments > Sheet Music'),
	('CAT_27256', 'CAT_27237', 'Drum Kits', 'Musical Instruments > Drum Kits'),
	('CAT_27273', 'CAT_27237', 'Guitar Combo Amps & Amp Heads', 'Musical Instruments > Guitar Combo Amps & Amp Heads'),
	('CAT_27278', 'CAT_27237', 'Mixers & Processors', 'Musical Instruments > Mixers & Processors'),
	('CAT_27279', 'CAT_27237', 'Monitors, Stage Speakers & PA Packages', 'Musical Instruments > Monitors, Stage Speakers & PA Packages'),
	('CAT_27316', '', 'Kitchen Gadgets & Utensils - Category Branch', 'Kitchen Gadgets & Utensils - Category Branch'),
	('CAT_27317', 'CAT_30840', 'Shavers and Groomers', 'Health, Beauty & Travel > Shavers and Groomers'),
	('CAT_27320', 'CAT_33179', 'Mice', 'Computers > Graphics Tablets & Accessories - Category Branch > Mice'),
	('CAT_27327', 'CAT_30840', 'Curling Irons', 'Health, Beauty & Travel > Curling Irons'),
	('CAT_27328', 'CAT_30840', 'Hair Straighteners', 'Health, Beauty & Travel > Hair Straighteners'),
	('CAT_27329', 'CAT_30840', 'Hair Dryers', 'Health, Beauty & Travel > Hair Dryers'),
	('CAT_27336', 'CAT_27237', 'Recording Software', 'Musical Instruments > Recording Software'),
	('CAT_27383', '', 'Home Automation & Accessories - Category Branch', 'Home Automation & Accessories - Category Branch'),
	('CAT_27384', 'CAT_660285', 'Pet Care-Other', 'Pets > Pet Care-Other'),
	('CAT_27385', 'CAT_670071', 'Health & Fitness', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Health & Fitness'),
	('CAT_27398', 'CAT_670071', 'Heart Rate Monitors', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Heart Rate Monitors'),
	('CAT_27400', 'CAT_670071', 'Treadmills', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Treadmills'),
	('CAT_27405', 'CAT_654823', 'GPS Tracking', 'Wearable Technology > GPS Tracking'),
	('CAT_27425', 'CAT_30840', 'Electric Toothbrushes', 'Health, Beauty & Travel > Electric Toothbrushes'),
	('CAT_27586', 'CAT_27115', 'Irons & Steamers', 'Appliances > Irons & Steamers'),
	('CAT_27595', 'CAT_27115', 'Water Filters', 'Appliances > Water Filters'),
	('CAT_27596', 'CAT_670071', 'Yoga Mats', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Yoga Mats'),
	('CAT_27603', '', 'Tools & Garden', 'Tools & Garden'),
	('CAT_28138', 'CAT_25320', 'Portable Blu-ray & DVD Players', 'Home Theatre > Blu-ray & DVD Players - Category Branch > Portable Blu-ray & DVD Players'),
	('CAT_28462', 'CAT_30658', 'eReader Cases & Protectors', 'Computers > eReader Cases & Protectors'),
	('CAT_28512', 'CAT_27237', 'Condenser Mics', 'Musical Instruments > Condenser Mics'),
	('CAT_28578', 'CAT_654823', 'Sports Performance Monitors', 'Wearable Technology > Sports Performance Monitors'),
	('CAT_28757', 'CAT_27237', 'Guitar Pedals', 'Musical Instruments > Guitar Pedals'),
	('CAT_28777', 'CAT_29958', 'Apple iPad', 'Computers > Tablets - Category Branch > Apple iPad'),
	('CAT_28839', 'CAT_27603', 'Workwear & Apparel - Category Branch', 'Tools & Garden > Workwear & Apparel - Category Branch'),
	('CAT_28841', 'CAT_28839', 'T-Shirts', 'Tools & Garden > Workwear & Apparel - Category Branch > T-Shirts'),
	('CAT_29000', 'CAT_26336', 'Cell Phones & Smartphones', 'Cellular Phones > Cell Phones & Smartphones'),
	('CAT_29001', '', 'Geek Squad', 'Geek Squad'),
	('CAT_2903', 'CAT_31177', 'Shredders', 'Office Supplies > Shredders'),
	('CAT_29037', 'CAT_25320', 'Blu-ray & DVD Players', 'Home Theatre > Blu-ray & DVD Players - Category Branch > Blu-ray & DVD Players'),
	('CAT_29041', 'CAT_659225', 'Binoculars & Monoculars', 'Toys, Sports & Recreation > Sports & Recreation > Binoculars & Monoculars'),
	('CAT_29095', 'CAT_26336', 'BlackBerry Power & Cables', 'Cellular Phones > BlackBerry Power & Cables'),
	('CAT_29103', 'CAT_15', 'Video Game Consoles', 'Gaming > Video Game Consoles'),
	('CAT_29216', 'CAT_27115', 'Coffee Makers & Espresso Machines', 'Appliances > Coffee Makers & Espresso Machines'),
	('CAT_29283', 'CAT_14', 'Flashes', 'Cameras & Camcorders > Flashes'),
	('CAT_29437', 'CAT_30658', 'Laptop Carrying Cases & Bags', 'Computers > Laptop Carrying Cases & Bags'),
	('CAT_29501', 'CAT_30837', 'Baby Safety Gates', 'Baby & Kids > Baby Safety Gates'),
	('CAT_29502', 'CAT_30837', 'Baby Bath Tubs', 'Baby & Kids > Baby Bath Tubs'),
	('CAT_29556', 'CAT_30658', 'Mobile Internet Hubs & Sticks', 'Computers > Mobile Internet Hubs & Sticks'),
	('CAT_29588', 'CAT_30658', 'Range Extenders & Powerline Networking', 'Computers > Range Extenders & Powerline Networking'),
	('CAT_29637', '', 'Bedding & Linens', 'Bedding & Linens'),
	('CAT_29740', 'CAT_27115', 'Coffee, Tea, Other Beverages', 'Appliances > Coffee, Tea, Other Beverages'),
	('CAT_29777', 'CAT_11', 'Internet Protocol TV (IPTV)', 'Home Theatre > Internet Protocol TV (IPTV)'),
	('CAT_29877', 'CAT_11', 'Combination TVs', 'Home Theatre > Combination TVs'),
	('CAT_29879', 'CAT_11', 'Televisions', 'Home Theatre > Televisions'),
	('CAT_29958', 'CAT_30658', 'Tablets - Category Branch', 'Computers > Tablets - Category Branch'),
	('CAT_30057', 'CAT_30658', 'Other Specialty Printers', 'Computers > Other Specialty Printers'),
	('CAT_30177', 'CAT_26336', 'Cell Phone Cases', 'Cellular Phones > Cell Phone Cases'),
	('CAT_30281', 'CAT_27115', 'Kitchen Scales', 'Appliances > Kitchen Scales'),
	('CAT_30577', 'CAT_27115', 'Sewing Machines', 'Appliances > Sewing Machines'),
	('CAT_30658', '', 'Computers', 'Computers'),
	('CAT_30663', 'CAT_30658', 'iPad & Tablet Cases, Screen Protectors & Keyboards', 'Computers > iPad & Tablet Cases, Screen Protectors & Keyboards'),
	('CAT_30664', 'CAT_30658', 'iPad & Tablet Accessories', 'Computers > iPad & Tablet Accessories'),
	('CAT_30821', 'CAT_27115', 'Fans', 'Appliances > Fans'),
	('CAT_30822', 'CAT_27115', 'Heater & Fireplace Parts', 'Appliances > Heater & Fireplace Parts'),
	('CAT_30837', '', 'Baby & Kids', 'Baby & Kids'),
	('CAT_30839', '', 'Home & Furniture', 'Home & Furniture'),
	('CAT_30840', '', 'Health, Beauty & Travel', 'Health, Beauty & Travel'),
	('CAT_30844', 'CAT_30840', 'Spas & Getaway Experience Gifts', 'Health, Beauty & Travel > Spas & Getaway Experience Gifts'),
	('CAT_30859', 'CAT_14', 'Cases, Bags & Straps', 'Cameras & Camcorders > Cases, Bags & Straps'),
	('CAT_30860', 'CAT_14', 'Batteries & Chargers', 'Cameras & Camcorders > Batteries & Chargers'),
	('CAT_30861', 'CAT_14', 'Tripods & Monopods', 'Cameras & Camcorders > Tripods & Monopods'),
	('CAT_31091', 'CAT_659225', 'Breathalyzers', 'Toys, Sports & Recreation > Sports & Recreation > Breathalyzers'),
	('CAT_31117', 'CAT_31177', 'Binding Machines', 'Office Supplies > Binding Machines'),
	('CAT_31120', 'CAT_31177', 'Laminators', 'Office Supplies > Laminators'),
	('CAT_31127', 'CAT_31177', 'Label Makers', 'Office Supplies > Label Makers'),
	('CAT_31177', '', 'Office Supplies', 'Office Supplies'),
	('CAT_31197', 'CAT_31177', 'More Office Supplies', 'Office Supplies > More Office Supplies'),
	('CAT_31198', 'CAT_30840', 'Luggage - Category Branch', 'Health, Beauty & Travel > Luggage - Category Branch'),
	('CAT_31324', 'CAT_28839', 'Headwear', 'Tools & Garden > Workwear & Apparel - Category Branch > Headwear'),
	('CAT_31325', 'CAT_28839', 'Gloves', 'Tools & Garden > Workwear & Apparel - Category Branch > Gloves'),
	('CAT_31329', 'CAT_28839', 'Jackets, Vests & Tops', 'Tools & Garden > Workwear & Apparel - Category Branch > Jackets, Vests & Tops'),
	('CAT_313858', 'CAT_1954', 'Freezers', 'Appliances > Freezers > Freezers'),
	('CAT_313874', 'CAT_31198', 'Luggage', 'Health, Beauty & Travel > Luggage - Category Branch > Luggage'),
	('CAT_31437', '', 'Kitchen Knives - Category Branch', 'Kitchen Knives - Category Branch'),
	('CAT_31438', 'CAT_30839', 'Barbecue Parts & Accessories - Category Branch', 'Home & Furniture > Barbecue Parts & Accessories - Category Branch'),
	('CAT_31441', '', 'Dinnerware & Glassware - Category Branch', 'Dinnerware & Glassware - Category Branch'),
	('CAT_31442', 'CAT_31443', 'Cookware & Ovenware - Individual Pieces', 'Cookware & Bakeware - Category Branch > Cookware & Ovenware - Individual Pieces'),
	('CAT_31443', '', 'Cookware & Bakeware - Category Branch', 'Cookware & Bakeware - Category Branch'),
	('CAT_31444', 'CAT_31437', 'Kitchen Knife Sets', 'Kitchen Knives - Category Branch > Kitchen Knife Sets'),
	('CAT_31445', 'CAT_31437', 'Kitchen Knives - Individual Pieces', 'Kitchen Knives - Category Branch > Kitchen Knives - Individual Pieces'),
	('CAT_31446', 'CAT_31437', 'Knife Blocks', 'Kitchen Knives - Category Branch > Knife Blocks'),
	('CAT_31448', 'CAT_31438', 'Barbecue Accessories Sets', 'Home & Furniture > Barbecue Parts & Accessories - Category Branch > Barbecue Accessories Sets'),
	('CAT_31451', '', 'Flatware', 'Flatware'),
	('CAT_31457', 'CAT_31441', 'Dinnerware & Serveware Sets', 'Dinnerware & Glassware - Category Branch > Dinnerware & Serveware Sets'),
	('CAT_31463', 'CAT_31443', 'Bakeware Sets', 'Cookware & Bakeware - Category Branch > Bakeware Sets'),
	('CAT_314700', 'CAT_33179', 'Graphics Tablets & Accessories', 'Computers > Graphics Tablets & Accessories - Category Branch > Graphics Tablets & Accessories'),
	('CAT_314719', 'CAT_1082', 'DVD Drives', 'Computers > DVD Drives - Category Branch > DVD Drives'),
	('CAT_314802', 'CAT_29958', 'Tablets', 'Computers > Tablets - Category Branch > Tablets'),
	('CAT_314829', 'CAT_33527', 'Eyewear', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Eyewear - Category Branch > Eyewear'),
	('CAT_314831', 'CAT_35585', 'Jewelry', 'Health, Beauty & Travel > Jewelry - Category Branch > Jewelry'),
	('CAT_314919', 'CAT_27383', 'Home Automation Accessories', 'Home Automation & Accessories - Category Branch > Home Automation Accessories'),
	('CAT_314924', 'CAT_22210', 'Home Decor', 'Home Decor - Category Branch > Home Decor'),
	('CAT_314930', 'CAT_31443', 'Bakeware - Individual Pieces', 'Cookware & Bakeware - Category Branch > Bakeware - Individual Pieces'),
	('CAT_314933', 'CAT_31438', 'Barbecue Parts & Accessories', 'Home & Furniture > Barbecue Parts & Accessories - Category Branch > Barbecue Parts & Accessories'),
	('CAT_314937', 'CAT_27316', 'Kitchen & Dining Accessories', 'Kitchen Gadgets & Utensils - Category Branch > Kitchen & Dining Accessories'),
	('CAT_314941', 'CAT_31441', 'Dinnerware & Serveware - Individual Pieces', 'Dinnerware & Glassware - Category Branch > Dinnerware & Serveware - Individual Pieces'),
	('CAT_314953', 'CAT_31941', 'Hand Tools', 'Tools & Garden > Hand Tools - Category Branch > Hand Tools'),
	('CAT_314955', 'CAT_32514', 'Power Tool Accessories', 'Tools & Garden > Power Tool Accessories - Category Branch > Power Tool Accessories'),
	('CAT_314963', 'CAT_28839', 'Workwear & Apparel', 'Tools & Garden > Workwear & Apparel - Category Branch > Workwear & Apparel'),
	('CAT_315694', 'CAT_1047', 'Home Speakers', 'Home Theatre > Home Speakers - Category Branch > Home Speakers'),
	('CAT_315699', 'CAT_2002', 'Digital Cable', 'Home Theatre > Digital Cable - Category Branch > Digital Cable'),
	('CAT_315836', 'CAT_32077', 'TV Stands', 'Home Theatre > TV Stands - Category Branch > TV Stands'),
	('CAT_31939', 'CAT_27603', 'Power Tools - Category Branch', 'Tools & Garden > Power Tools - Category Branch'),
	('CAT_31941', 'CAT_27603', 'Hand Tools - Category Branch', 'Tools & Garden > Hand Tools - Category Branch'),
	('CAT_31942', 'CAT_30840', 'Fashion Accessories - Category Branch', 'Health, Beauty & Travel > Fashion Accessories - Category Branch'),
	('CAT_31943', 'CAT_660196', 'Patio Cushions & More - Category Branch', 'Furniture - Category Branch > Patio Cushions & More - Category Branch'),
	('CAT_31946', 'CAT_660196', 'Office Desks & Sets', 'Furniture - Category Branch > Office Desks & Sets'),
	('CAT_31948', 'CAT_31941', 'Utility Knives & Multi-Tools', 'Tools & Garden > Hand Tools - Category Branch > Utility Knives & Multi-Tools'),
	('CAT_31950', '', 'Shower Heads & Hand Showers', 'Shower Heads & Hand Showers'),
	('CAT_31952', 'CAT_31941', 'Hand Planes', 'Tools & Garden > Hand Tools - Category Branch > Hand Planes'),
	('CAT_31953', 'CAT_659225', 'Sleeping Bags', 'Toys, Sports & Recreation > Sports & Recreation > Sleeping Bags'),
	('CAT_31954', 'CAT_659225', 'More Camping Accessories', 'Toys, Sports & Recreation > Sports & Recreation > More Camping Accessories'),
	('CAT_31958', 'CAT_31939', 'Electric Drills', 'Tools & Garden > Power Tools - Category Branch > Electric Drills'),
	('CAT_31959', 'CAT_31939', 'Electric Saws', 'Tools & Garden > Power Tools - Category Branch > Electric Saws'),
	('CAT_31960', 'CAT_31939', 'Heat Guns', 'Tools & Garden > Power Tools - Category Branch > Heat Guns'),
	('CAT_31961', 'CAT_31939', 'Biscuit Joiners', 'Tools & Garden > Power Tools - Category Branch > Biscuit Joiners'),
	('CAT_31962', 'CAT_31939', 'Leaf Blowers', 'Tools & Garden > Power Tools - Category Branch > Leaf Blowers'),
	('CAT_31963', 'CAT_31939', 'Disc Grinders', 'Tools & Garden > Power Tools - Category Branch > Disc Grinders'),
	('CAT_31964', 'CAT_31939', 'Impact Wrenches', 'Tools & Garden > Power Tools - Category Branch > Impact Wrenches'),
	('CAT_31965', 'CAT_31939', 'Shop Vacuums', 'Tools & Garden > Power Tools - Category Branch > Shop Vacuums'),
	('CAT_31966', 'CAT_31939', 'Hand Planers', 'Tools & Garden > Power Tools - Category Branch > Hand Planers'),
	('CAT_31967', 'CAT_31939', 'Handheld Sanders & Polishers', 'Tools & Garden > Power Tools - Category Branch > Handheld Sanders & Polishers'),
	('CAT_31968', 'CAT_31939', 'Pneumatic Staplers', 'Tools & Garden > Power Tools - Category Branch > Pneumatic Staplers'),
	('CAT_31969', 'CAT_31939', 'Pneumatic Nailers', 'Tools & Garden > Power Tools - Category Branch > Pneumatic Nailers'),
	('CAT_31970', 'CAT_31939', 'Air Compressors', 'Tools & Garden > Power Tools - Category Branch > Air Compressors'),
	('CAT_31971', 'CAT_31939', 'Routers & Laminate Trimmers', 'Tools & Garden > Power Tools - Category Branch > Routers & Laminate Trimmers'),
	('CAT_31972', 'CAT_31939', 'Stands and Workstations', 'Tools & Garden > Power Tools - Category Branch > Stands and Workstations'),
	('CAT_31973', 'CAT_31939', 'Other Power Tools', 'Tools & Garden > Power Tools - Category Branch > Other Power Tools'),
	('CAT_31978', 'CAT_31941', 'Drivers & Screwdrivers', 'Tools & Garden > Hand Tools - Category Branch > Drivers & Screwdrivers'),
	('CAT_31979', 'CAT_31941', 'Chisels, Bolsters & Files', 'Tools & Garden > Hand Tools - Category Branch > Chisels, Bolsters & Files'),
	('CAT_31980', 'CAT_31941', 'Hand Saws', 'Tools & Garden > Hand Tools - Category Branch > Hand Saws'),
	('CAT_31981', 'CAT_31941', 'Levels', 'Tools & Garden > Hand Tools - Category Branch > Levels'),
	('CAT_31982', 'CAT_31941', 'Stand Vises', 'Tools & Garden > Hand Tools - Category Branch > Stand Vises'),
	('CAT_31983', 'CAT_31941', 'Clamps & Vises', 'Tools & Garden > Hand Tools - Category Branch > Clamps & Vises'),
	('CAT_31984', 'CAT_31941', 'Pliers & Wire Cutters', 'Tools & Garden > Hand Tools - Category Branch > Pliers & Wire Cutters'),
	('CAT_31985', 'CAT_31941', 'Hammers & Mallets', 'Tools & Garden > Hand Tools - Category Branch > Hammers & Mallets'),
	('CAT_31986', 'CAT_31941', 'Wrenches', 'Tools & Garden > Hand Tools - Category Branch > Wrenches'),
	('CAT_31987', 'CAT_31941', 'Mitre Boxes', 'Tools & Garden > Hand Tools - Category Branch > Mitre Boxes'),
	('CAT_31988', 'CAT_32077', 'Fireplace TV Stands', 'Home Theatre > TV Stands - Category Branch > Fireplace TV Stands'),
	('CAT_31990', 'CAT_670071', 'Yoga & Stability Balls', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Yoga & Stability Balls'),
	('CAT_31992', 'CAT_659225', 'Tarps', 'Toys, Sports & Recreation > Sports & Recreation > Tarps'),
	('CAT_31995', '', 'Candles', 'Candles'),
	('CAT_31998', 'CAT_659225', 'Sports Impact Protection', 'Toys, Sports & Recreation > Sports & Recreation > Sports Impact Protection'),
	('CAT_32000', 'CAT_660196', 'Headboards & Footboards', 'Furniture - Category Branch > Headboards & Footboards'),
	('CAT_32001', 'CAT_31942', 'Scarves', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Scarves'),
	('CAT_32002', 'CAT_35585', 'Rings', 'Health, Beauty & Travel > Jewelry - Category Branch > Rings'),
	('CAT_32003', 'CAT_35585', 'Earrings', 'Health, Beauty & Travel > Jewelry - Category Branch > Earrings'),
	('CAT_32004', 'CAT_35585', 'Necklaces', 'Health, Beauty & Travel > Jewelry - Category Branch > Necklaces'),
	('CAT_32005', 'CAT_35585', 'Bracelets, Bangles & Cuffs', 'Health, Beauty & Travel > Jewelry - Category Branch > Bracelets, Bangles & Cuffs'),
	('CAT_32006', 'CAT_31942', 'More Fashion Accessories', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > More Fashion Accessories'),
	('CAT_32007', 'CAT_31198', 'Handbags & Purses', 'Health, Beauty & Travel > Luggage - Category Branch > Handbags & Purses'),
	('CAT_32010', 'CAT_659219', 'Collectable Models & Replicas', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Collectable Models & Replicas'),
	('CAT_32016', 'CAT_9', 'Car Floor Mats', 'Car, Marine & GPS > Car Floor Mats'),
	('CAT_32044', 'CAT_31941', 'Other Hand Tools', 'Tools & Garden > Hand Tools - Category Branch > Other Hand Tools'),
	('CAT_32077', 'CAT_11', 'TV Stands - Category Branch', 'Home Theatre > TV Stands - Category Branch'),
	('CAT_32081', 'CAT_659219', 'Remote Control Toys', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Remote Control Toys'),
	('CAT_32082', 'CAT_659219', 'Action Figures, Dolls & Robots', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Action Figures, Dolls & Robots'),
	('CAT_32083', 'CAT_26336', 'Chargers & Power Adapters', 'Cellular Phones > Chargers & Power Adapters'),
	('CAT_32084', 'CAT_659219', 'Building Blocks & Sets', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Building Blocks & Sets'),
	('CAT_32085', 'CAT_27603', 'Flashlights & Lanterns', 'Tools & Garden > Flashlights & Lanterns'),
	('CAT_321023', 'CAT_23274', 'Headphones & Headsets', 'iPod & Portable Audio > Headphones & Headsets - Category Branch > Headphones & Headsets'),
	('CAT_32509', 'CAT_660196', 'More Kitchen & Dining Furniture - Category Branch', 'Furniture - Category Branch > More Kitchen & Dining Furniture - Category Branch'),
	('CAT_32512', 'CAT_30837', 'Baby Strollers', 'Baby & Kids > Baby Strollers'),
	('CAT_32514', 'CAT_27603', 'Power Tool Accessories - Category Branch', 'Tools & Garden > Power Tool Accessories - Category Branch'),
	('CAT_32515', 'CAT_30837', 'Breast Pumps', 'Baby & Kids > Breast Pumps'),
	('CAT_32516', 'CAT_31177', 'Paper Cutters & Trimmers', 'Office Supplies > Paper Cutters & Trimmers'),
	('CAT_32517', '', 'Pillows & Cushions', 'Pillows & Cushions'),
	('CAT_32724', 'CAT_659225', 'Sports & Beach Umbrellas', 'Toys, Sports & Recreation > Sports & Recreation > Sports & Beach Umbrellas'),
	('CAT_32742', 'CAT_660196', 'Media Storage', 'Furniture - Category Branch > Media Storage'),
	('CAT_32774', 'CAT_654823', 'GPS Watches & Running GPS', 'Wearable Technology > GPS Watches & Running GPS'),
	('CAT_32803', 'CAT_30837', '(delete)Baby Travel Beds', 'Baby & Kids > (delete)Baby Travel Beds'),
	('CAT_32804', 'CAT_30837', 'Baby Playpens, Playards & Travel Beds', 'Baby & Kids > Baby Playpens, Playards & Travel Beds'),
	('CAT_32808', 'CAT_659225', 'Camping Stoves', 'Toys, Sports & Recreation > Sports & Recreation > Camping Stoves'),
	('CAT_32810', 'CAT_30837', 'Baby Cribs & Bassinets', 'Baby & Kids > Baby Cribs & Bassinets'),
	('CAT_32826', 'CAT_30837', 'Nursing Accessories', 'Baby & Kids > Nursing Accessories'),
	('CAT_32827', 'CAT_22210', 'Posters', 'Home Decor - Category Branch > Posters'),
	('CAT_32831', 'CAT_30837', 'Food Mills', 'Baby & Kids > Food Mills'),
	('CAT_32835', 'CAT_32514', 'Drill Bits', 'Tools & Garden > Power Tool Accessories - Category Branch > Drill Bits'),
	('CAT_32836', 'CAT_32514', 'Drill Bit Sets', 'Tools & Garden > Power Tool Accessories - Category Branch > Drill Bit Sets'),
	('CAT_32838', 'CAT_31942', 'Lunch Bags & Boxes', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Lunch Bags & Boxes'),
	('CAT_32843', 'CAT_659225', 'Microscopes', 'Toys, Sports & Recreation > Sports & Recreation > Microscopes'),
	('CAT_32844', 'CAT_659225', 'Telescopes', 'Toys, Sports & Recreation > Sports & Recreation > Telescopes'),
	('CAT_32857', 'CAT_9', 'Cycling GPS & Bike Computers', 'Car, Marine & GPS > Cycling GPS & Bike Computers'),
	('CAT_32858', 'CAT_30837', 'Baby Car Seats & Booster Seats', 'Baby & Kids > Baby Car Seats & Booster Seats'),
	('CAT_32859', 'CAT_30837', 'Baby Carriers & Slings', 'Baby & Kids > Baby Carriers & Slings'),
	('CAT_32860', 'CAT_30837', 'Baby Diaper Bags', 'Baby & Kids > Baby Diaper Bags'),
	('CAT_32861', 'CAT_30837', 'Baby Stroller & Car Seat Accessories', 'Baby & Kids > Baby Stroller & Car Seat Accessories'),
	('CAT_32863', 'CAT_30837', 'Other Baby Products', 'Baby & Kids > Other Baby Products'),
	('CAT_32864', 'CAT_659219', 'RC Parts & Accessories', 'Toys, Sports & Recreation > Toys, Games & Collectibles > RC Parts & Accessories'),
	('CAT_328641', 'CAT_25794', 'Camera Lenses', 'Cameras & Camcorders > Camera Lenses - Category Branch > Camera Lenses'),
	('CAT_328644', 'CAT_35588', 'Bikes & Trikes', 'Toys, Sports & Recreation > Sports & Recreation > Bikes & Trikes - Category Branch > Bikes & Trikes'),
	('CAT_32865', 'CAT_30837', 'Baby Bouncers', 'Baby & Kids > Baby Bouncers'),
	('CAT_32866', 'CAT_30837', 'Baby Diapers', 'Baby & Kids > Baby Diapers'),
	('CAT_32867', 'CAT_30837', 'Baby Potties & Accessories', 'Baby & Kids > Baby Potties & Accessories'),
	('CAT_32868', 'CAT_31177', 'Shredder Accessories', 'Office Supplies > Shredder Accessories'),
	('CAT_32869', 'CAT_682461', 'Cosmetics & Makeup', 'Health, Beauty & Travel > Skin Care & Cosmetics - Category Branch > Cosmetics & Makeup'),
	('CAT_32870', 'CAT_30840', 'Hair Care', 'Health, Beauty & Travel > Hair Care'),
	('CAT_32871', 'CAT_30840', 'Umbrellas and Parasols', 'Health, Beauty & Travel > Umbrellas and Parasols'),
	('CAT_32872', 'CAT_27115', 'Heaters & Fireplaces', 'Appliances > Heaters & Fireplaces'),
	('CAT_32873', 'CAT_30837', 'Baby Monitors', 'Baby & Kids > Baby Monitors'),
	('CAT_32874', 'CAT_30840', 'Scales', 'Health, Beauty & Travel > Scales'),
	('CAT_32875', 'CAT_30840', 'Medical Thermometers', 'Health, Beauty & Travel > Medical Thermometers'),
	('CAT_32876', 'CAT_30840', 'Watches', 'Health, Beauty & Travel > Watches'),
	('CAT_32877', 'CAT_9', 'Other Automotive Accessories', 'Car, Marine & GPS > Other Automotive Accessories'),
	('CAT_32878', 'CAT_9', 'Car Window Tint Films', 'Car, Marine & GPS > Car Window Tint Films'),
	('CAT_32879', 'CAT_659219', 'Board Games & Card Games', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Board Games & Card Games'),
	('CAT_32880', 'CAT_659225', 'Sports Memorabilia', 'Toys, Sports & Recreation > Sports & Recreation > Sports Memorabilia'),
	('CAT_32881', 'CAT_11', 'Projector Screens', 'Home Theatre > Projector Screens'),
	('CAT_32883', '', 'Floor Sweepers & Mops - Category Branch', 'Floor Sweepers & Mops - Category Branch'),
	('CAT_32884', '', 'Lamps & Lighting', 'Lamps & Lighting'),
	('CAT_328904', 'CAT_31437', 'Knives & Cutlery', 'Kitchen Knives - Category Branch > Knives & Cutlery'),
	('CAT_328906', 'CAT_660196', 'More Bedroom Furniture - Category Branch', 'Furniture - Category Branch > More Bedroom Furniture - Category Branch'),
	('CAT_328963', 'CAT_35719', 'Bathroom Accessories', 'Home & Furniture > Bathroom Accessories - Category Branch > Bathroom Accessories'),
	('CAT_32916', 'CAT_30840', 'Massage Chairs', 'Health, Beauty & Travel > Massage Chairs'),
	('CAT_32936', 'CAT_30840', 'Manual Razors & Blades', 'Health, Beauty & Travel > Manual Razors & Blades'),
	('CAT_32937', 'CAT_30840', 'Manual Toothbrushes', 'Health, Beauty & Travel > Manual Toothbrushes'),
	('CAT_32966', 'CAT_30840', 'Replacement Brush Heads', 'Health, Beauty & Travel > Replacement Brush Heads'),
	('CAT_329705', 'CAT_659896', 'Air Hockey Tables', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Air Hockey Tables'),
	('CAT_33066', 'CAT_30840', 'Teeth Whitening Strips', 'Health, Beauty & Travel > Teeth Whitening Strips'),
	('CAT_33067', 'CAT_32883', 'Sweepers, Dusters & Mops', 'Floor Sweepers & Mops - Category Branch > Sweepers, Dusters & Mops'),
	('CAT_33068', 'CAT_32883', 'Sweeper & Duster Refills & Accessories', 'Floor Sweepers & Mops - Category Branch > Sweeper & Duster Refills & Accessories'),
	('CAT_33070', 'CAT_30658', 'Gaming Chairs', 'Computers > Gaming Chairs'),
	('CAT_33122', 'CAT_30658', 'Serial & Parallel Port Controller Cards', 'Computers > Serial & Parallel Port Controller Cards'),
	('CAT_33123', 'CAT_30658', 'SATA & IDE Controller Cards', 'Computers > SATA & IDE Controller Cards'),
	('CAT_33157', 'CAT_659225', 'Solar Panels & Power Packs', 'Toys, Sports & Recreation > Sports & Recreation > Solar Panels & Power Packs'),
	('CAT_33159', 'CAT_30840', 'Toothpaste', 'Health, Beauty & Travel > Toothpaste'),
	('CAT_33161', 'CAT_33527', 'Sunglasses', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Eyewear - Category Branch > Sunglasses'),
	('CAT_33175', 'CAT_30658', 'eReaders', 'Computers > eReaders'),
	('CAT_33176', 'CAT_26337', 'Wall Decals & Graphics', 'Toys, Sports & Recreation > Wall Decals & Graphics'),
	('CAT_33178', 'CAT_31198', 'Luggage Sets', 'Health, Beauty & Travel > Luggage - Category Branch > Luggage Sets'),
	('CAT_33179', 'CAT_30658', 'Graphics Tablets & Accessories - Category Branch', 'Computers > Graphics Tablets & Accessories - Category Branch'),
	('CAT_33180', 'CAT_30658', 'Keyboards', 'Computers > Keyboards'),
	('CAT_33182', 'CAT_27115', 'Specialty Vacuums & Floor Care', 'Appliances > Specialty Vacuums & Floor Care'),
	('CAT_33184', 'CAT_659219', 'Puzzles', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Puzzles'),
	('CAT_33527', 'CAT_31942', 'Eyewear - Category Branch', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Eyewear - Category Branch'),
	('CAT_33528', '', 'Decorative Cushion Covers', 'Decorative Cushion Covers'),
	('CAT_33530', 'CAT_659225', 'Two-way Radios', 'Toys, Sports & Recreation > Sports & Recreation > Two-way Radios'),
	('CAT_33532', '', 'Lawn Mowers', 'Lawn Mowers'),
	('CAT_33534', '', 'Lawn Mower Parts - Category Branch', 'Lawn Mower Parts - Category Branch'),
	('CAT_33535', 'CAT_660196', 'Patio Chairs', 'Furniture - Category Branch > Patio Chairs'),
	('CAT_33536', 'CAT_660196', 'Patio Tables', 'Furniture - Category Branch > Patio Tables'),
	('CAT_33537', 'CAT_30837', 'Baby & Child Clothes', 'Baby & Kids > Baby & Child Clothes'),
	('CAT_33539', 'CAT_27115', 'Kettles & Hot Water Dispensers', 'Appliances > Kettles & Hot Water Dispensers'),
	('CAT_33540', 'CAT_660196', 'Living Room Tables', 'Furniture - Category Branch > Living Room Tables'),
	('CAT_33541', 'CAT_31177', 'Filing & Storage', 'Office Supplies > Filing & Storage'),
	('CAT_33542', 'CAT_27115', 'Mixers', 'Appliances > Mixers'),
	('CAT_33544', 'CAT_660196', 'Living Room Chairs', 'Furniture - Category Branch > Living Room Chairs'),
	('CAT_33545', 'CAT_660196', 'Sofas, Sectionals & Futons - Category Branch', 'Furniture - Category Branch > Sofas, Sectionals & Futons - Category Branch'),
	('CAT_33546', 'CAT_660196', 'Ottomans & Living Room Benches', 'Furniture - Category Branch > Ottomans & Living Room Benches'),
	('CAT_33547', 'CAT_660196', 'Kitchen & Dining Room Tables', 'Furniture - Category Branch > Kitchen & Dining Room Tables'),
	('CAT_33548', 'CAT_660196', 'Kitchen & Dining Room Chairs', 'Furniture - Category Branch > Kitchen & Dining Room Chairs'),
	('CAT_33549', 'CAT_660196', 'Dining Sets', 'Furniture - Category Branch > Dining Sets'),
	('CAT_33550', 'CAT_660196', 'Patio Umbrellas', 'Furniture - Category Branch > Patio Umbrellas'),
	('CAT_33551', 'CAT_660196', 'Office Storage Cabinets & Hutches', 'Furniture - Category Branch > Office Storage Cabinets & Hutches'),
	('CAT_33552', 'CAT_27237', 'Wind Instruments', 'Musical Instruments > Wind Instruments'),
	('CAT_33553', 'CAT_660196', 'Office Chairs', 'Furniture - Category Branch > Office Chairs'),
	('CAT_33554', 'CAT_654823', 'Wearable Technology Accessories', 'Wearable Technology > Wearable Technology Accessories'),
	('CAT_33569', 'CAT_30840', 'Floss', 'Health, Beauty & Travel > Floss'),
	('CAT_33570', 'CAT_30840', 'Mouthwash', 'Health, Beauty & Travel > Mouthwash'),
	('CAT_33608', 'CAT_31939', 'Pressure Washers', 'Tools & Garden > Power Tools - Category Branch > Pressure Washers'),
	('CAT_33611', 'CAT_30837', 'Gliders', 'Baby & Kids > Gliders'),
	('CAT_33631', 'CAT_659225', 'Coolers', 'Toys, Sports & Recreation > Sports & Recreation > Coolers'),
	('CAT_33636', 'CAT_33534', 'Lawn Mower Parts', 'Lawn Mower Parts - Category Branch > Lawn Mower Parts'),
	('CAT_34806', 'CAT_30840', 'Sexual Wellness', 'Health, Beauty & Travel > Sexual Wellness'),
	('CAT_34807', 'CAT_30837', 'Baby & Child Shoes', 'Baby & Kids > Baby & Child Shoes'),
	('CAT_34808', 'CAT_31177', 'Boards, Wall Calendars & Deskpads', 'Office Supplies > Boards, Wall Calendars & Deskpads'),
	('CAT_34809', 'CAT_31177', 'Envelopes', 'Office Supplies > Envelopes'),
	('CAT_34816', 'CAT_31177', 'Writing Instruments', 'Office Supplies > Writing Instruments'),
	('CAT_34819', 'CAT_659219', 'Model Kits', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Model Kits'),
	('CAT_34820', 'CAT_659219', 'Model Rockets & Accessories', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Model Rockets & Accessories'),
	('CAT_34821', 'CAT_660196', 'Mattresses & Mattress Toppers', 'Furniture - Category Branch > Mattresses & Mattress Toppers'),
	('CAT_34822', 'CAT_660196', 'Mattress Foundations', 'Furniture - Category Branch > Mattress Foundations'),
	('CAT_34823', 'CAT_27115', 'Soda Makers & Accessories', 'Appliances > Soda Makers & Accessories'),
	('CAT_34824', 'CAT_27237', 'Musical Instrument Bags', 'Musical Instruments > Musical Instrument Bags'),
	('CAT_34825', 'CAT_660285', 'Pet Leashes, Collars, Harnesses', 'Pets > Pet Leashes, Collars, Harnesses'),
	('CAT_34837', 'CAT_659225', 'Solar Panel & Power Pack Accessories', 'Toys, Sports & Recreation > Sports & Recreation > Solar Panel & Power Pack Accessories'),
	('CAT_34906', 'CAT_30658', '3D Printers', 'Computers > 3D Printers'),
	('CAT_34907', 'CAT_30658', '3D Printer Cartridges', 'Computers > 3D Printer Cartridges'),
	('CAT_34908', 'CAT_30658', '3D Printer Accessories', 'Computers > 3D Printer Accessories'),
	('CAT_35581', 'CAT_30840', 'Jewelry Boxes', 'Health, Beauty & Travel > Jewelry Boxes'),
	('CAT_35582', 'CAT_659219', 'Toys-Ride On Toys & Go Karts - Category Branch', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Toys-Ride On Toys & Go Karts - Category Branch'),
	('CAT_35583', 'CAT_659219', 'Electronic Learning Toys', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Electronic Learning Toys'),
	('CAT_35584', 'CAT_659225', 'Scooters', 'Toys, Sports & Recreation > Sports & Recreation > Scooters'),
	('CAT_35585', 'CAT_30840', 'Jewelry - Category Branch', 'Health, Beauty & Travel > Jewelry - Category Branch'),
	('CAT_35586', '', 'Surveillance Systems & Cameras', 'Surveillance Systems & Cameras'),
	('CAT_35587', 'CAT_654823', 'Smartwatches, Fitness Trackers', 'Wearable Technology > Smartwatches, Fitness Trackers'),
	('CAT_35588', 'CAT_659225', 'Bikes & Trikes - Category Branch', 'Toys, Sports & Recreation > Sports & Recreation > Bikes & Trikes - Category Branch'),
	('CAT_35589', 'CAT_28839', 'Footwear', 'Tools & Garden > Workwear & Apparel - Category Branch > Footwear'),
	('CAT_35590', 'CAT_660285', 'Pet Apparel', 'Pets > Pet Apparel'),
	('CAT_35591', 'CAT_660285', 'Pet Treats & Supplements', 'Pets > Pet Treats & Supplements'),
	('CAT_35592', 'CAT_660285', 'Pet Carriers', 'Pets > Pet Carriers'),
	('CAT_35593', 'CAT_27603', 'Snow Blowers', 'Tools & Garden > Snow Blowers'),
	('CAT_35595', 'CAT_660285', 'Pet Skin & Coat Care', 'Pets > Pet Skin & Coat Care'),
	('CAT_35611', 'CAT_35585', 'Jewelry Sets', 'Health, Beauty & Travel > Jewelry - Category Branch > Jewelry Sets'),
	('CAT_35668', 'CAT_35588', 'Toys- Kids Bikes & Trikes', 'Toys, Sports & Recreation > Sports & Recreation > Bikes & Trikes - Category Branch > Toys- Kids Bikes & Trikes'),
	('CAT_35669', 'CAT_35582', 'Go Karts', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Toys-Ride On Toys & Go Karts - Category Branch > Go Karts'),
	('CAT_35671', '', 'Security Camera Accessories', 'Security Camera Accessories'),
	('CAT_35673', '', 'Home Security Sensors, Alarms and Monitors', 'Home Security Sensors, Alarms and Monitors'),
	('CAT_35688', 'CAT_659225', 'Crossbows', 'Toys, Sports & Recreation > Sports & Recreation > Crossbows'),
	('CAT_35706', 'CAT_660285', 'Pet Feeders & Water Containers', 'Pets > Pet Feeders & Water Containers'),
	('CAT_35707', 'CAT_660285', 'Pet Furniture', 'Pets > Pet Furniture'),
	('CAT_35708', 'CAT_660285', 'Pet Bedding', 'Pets > Pet Bedding'),
	('CAT_35710', 'CAT_660285', 'Pet Aquaruims & Terrariums', 'Pets > Pet Aquaruims & Terrariums'),
	('CAT_35711', 'CAT_660285', 'Pet Aquarium & Terrarium Acc.', 'Pets > Pet Aquarium & Terrarium Acc.'),
	('CAT_35713', 'CAT_31177', 'Notebooks & Notepads', 'Office Supplies > Notebooks & Notepads'),
	('CAT_35714', 'CAT_671405', 'Household Cleaning Agents', 'Household Cleaning- Category Branch > Household Cleaning Agents'),
	('CAT_35715', 'CAT_670071', 'Exercise Bikes', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Exercise Bikes'),
	('CAT_35716', 'CAT_27237', 'Acoustic Guitars', 'Musical Instruments > Acoustic Guitars'),
	('CAT_35717', 'CAT_660285', 'Pet Books', 'Pets > Pet Books'),
	('CAT_35718', 'CAT_30837', 'Nursery Furniture-Other', 'Baby & Kids > Nursery Furniture-Other'),
	('CAT_35719', 'CAT_30839', 'Bathroom Accessories - Category Branch', 'Home & Furniture > Bathroom Accessories - Category Branch'),
	('CAT_35721', 'CAT_31177', 'Binders', 'Office Supplies > Binders'),
	('CAT_35722', 'CAT_31177', 'Clipboards', 'Office Supplies > Clipboards'),
	('CAT_35723', 'CAT_31177', 'Glue & Adhesives', 'Office Supplies > Glue & Adhesives'),
	('CAT_35724', 'CAT_30837', 'Baby Feeding', 'Baby & Kids > Baby Feeding'),
	('CAT_35725', 'CAT_30837', 'Baby Toys', 'Baby & Kids > Baby Toys'),
	('CAT_35726', '', 'Surveillance Receiver & DVRs', 'Surveillance Receiver & DVRs'),
	('CAT_35728', 'CAT_659225', 'More Sports & Recreation', 'Toys, Sports & Recreation > Sports & Recreation > More Sports & Recreation'),
	('CAT_35729', 'CAT_660196', 'Beds & Bed Frames', 'Furniture - Category Branch > Beds & Bed Frames'),
	('CAT_35731', 'CAT_30837', 'Maternity Clothes & Accessories - Category Branch', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch'),
	('CAT_35732', 'CAT_660285', 'Pet Waste Bags', 'Pets > Pet Waste Bags'),
	('CAT_35733', 'CAT_30837', 'High Chairs & Booster Seats', 'Baby & Kids > High Chairs & Booster Seats'),
	('CAT_35734', 'CAT_27115', 'Blenders', 'Appliances > Blenders'),
	('CAT_35780', 'CAT_35582', 'Ride On Toys', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Toys-Ride On Toys & Go Karts - Category Branch > Ride On Toys'),
	('CAT_35787', 'CAT_33534', 'Snow Blower Parts', 'Lawn Mower Parts - Category Branch > Snow Blower Parts'),
	('CAT_35853', 'CAT_27237', 'Musical Instrument Accessories', 'Musical Instruments > Musical Instrument Accessories'),
	('CAT_36029', 'CAT_659896', 'Game Tables', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Game Tables'),
	('CAT_36986', 'CAT_23274', 'Gaming Console Headsets', 'iPod & Portable Audio > Headphones & Headsets - Category Branch > Gaming Console Headsets'),
	('CAT_37129', '', 'Bathroom Sink Faucets', 'Bathroom Sink Faucets'),
	('CAT_37130', '', 'Shower & Bath Faucets', 'Shower & Bath Faucets'),
	('CAT_37131', 'CAT_35719', 'Bath Hooks & Holders', 'Home & Furniture > Bathroom Accessories - Category Branch > Bath Hooks & Holders'),
	('CAT_37133', 'CAT_31177', 'Sheet Protectors', 'Office Supplies > Sheet Protectors'),
	('CAT_37134', 'CAT_31177', 'Report Covers', 'Office Supplies > Report Covers'),
	('CAT_37136', 'CAT_30837', 'Baby Stroller & Car Seat Combo', 'Baby & Kids > Baby Stroller & Car Seat Combo'),
	('CAT_37140', 'CAT_27383', 'Smart Lights & Controls', 'Home Automation & Accessories - Category Branch > Smart Lights & Controls'),
	('CAT_37144', 'CAT_27383', 'Smart Home Controls & Access', 'Home Automation & Accessories - Category Branch > Smart Home Controls & Access'),
	('CAT_37191', 'CAT_35588', 'Electric Bikes', 'Toys, Sports & Recreation > Sports & Recreation > Bikes & Trikes - Category Branch > Electric Bikes'),
	('CAT_37201', 'CAT_31942', 'Cufflinks, Pins, Brooches', 'Health, Beauty & Travel > Fashion Accessories - Category Branch > Cufflinks, Pins, Brooches'),
	('CAT_37205', 'CAT_27115', 'Dual Fuel Ranges', 'Appliances > Dual Fuel Ranges'),
	('CAT_37206', 'CAT_659225', 'Head Lamps', 'Toys, Sports & Recreation > Sports & Recreation > Head Lamps'),
	('CAT_37209', 'CAT_35731', 'Maternity Tops', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch > Maternity Tops'),
	('CAT_37211', 'CAT_35731', 'Maternity Swimwear & Underwear', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch > Maternity Swimwear & Underwear'),
	('CAT_37212', 'CAT_35731', 'Maternity Dresses', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch > Maternity Dresses'),
	('CAT_37326', 'CAT_659225', 'Crossbow Bolts', 'Toys, Sports & Recreation > Sports & Recreation > Crossbow Bolts'),
	('CAT_37327', 'CAT_659225', 'Crossbow Accessories', 'Toys, Sports & Recreation > Sports & Recreation > Crossbow Accessories'),
	('CAT_37328', 'CAT_35731', 'Maternity Bottoms', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch > Maternity Bottoms'),
	('CAT_37329', 'CAT_35731', 'Maternity Sleepwear', 'Baby & Kids > Maternity Clothes & Accessories - Category Branch > Maternity Sleepwear'),
	('CAT_37332', 'CAT_659896', 'Table Tennis', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Table Tennis'),
	('CAT_37333', 'CAT_659896', 'Foosball Tables', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Foosball Tables'),
	('CAT_37334', 'CAT_659896', 'Dart Boards', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Dart Boards'),
	('CAT_37740', 'CAT_22', 'Generic', 'Multi-Dept and Generic > Generic'),
	('CAT_37789', 'CAT_22', 'Multibox-Other', 'Multi-Dept and Generic > Multibox-Other'),
	('CAT_37817', 'CAT_31177', 'Planners & Refills', 'Office Supplies > Planners & Refills'),
	('CAT_37820', 'CAT_31177', 'Tape', 'Office Supplies > Tape'),
	('CAT_37937', 'CAT_31198', 'Wallets & Clutches', 'Health, Beauty & Travel > Luggage - Category Branch > Wallets & Clutches'),
	('CAT_451680', 'CAT_30658', 'Travel Power Adapters', 'Computers > Travel Power Adapters'),
	('CAT_456160', 'CAT_30840', 'Protein Shakes & Health Food', 'Health, Beauty & Travel > Protein Shakes & Health Food'),
	('CAT_479916', 'CAT_9', 'Car Decks - Vehicle Specific', 'Car, Marine & GPS > Car Decks - Vehicle Specific'),
	('CAT_481936', 'CAT_9', 'Car Subwoofer Enclosures - Vehicle-Specific', 'Car, Marine & GPS > Car Subwoofer Enclosures - Vehicle-Specific'),
	('CAT_482214', 'CAT_9', 'Car Dash Trim Kits', 'Car, Marine & GPS > Car Dash Trim Kits'),
	('CAT_482331', 'CAT_9', 'Auto Parts', 'Car, Marine & GPS > Auto Parts'),
	('CAT_496383', 'CAT_26336', 'Cell Phone Signal Boosters', 'Cellular Phones > Cell Phone Signal Boosters'),
	('CAT_609229', 'CAT_660196', 'Living Room Sets', 'Furniture - Category Branch > Living Room Sets'),
	('CAT_609281', 'CAT_660196', 'Bedroom Sets', 'Furniture - Category Branch > Bedroom Sets'),
	('CAT_615197', 'CAT_660196', 'Bookcases & Shelving', 'Furniture - Category Branch > Bookcases & Shelving'),
	('CAT_616514', 'CAT_659219', 'Drones', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Drones'),
	('CAT_619653', 'CAT_659219', 'Drone Parts & Accessories', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Drone Parts & Accessories'),
	('CAT_640692', 'CAT_27383', 'Energy & Resource Management', 'Home Automation & Accessories - Category Branch > Energy & Resource Management'),
	('CAT_642432', 'CAT_11', 'Media Streamers & Players', 'Home Theatre > Media Streamers & Players'),
	('CAT_654823', '', 'Wearable Technology', 'Wearable Technology'),
	('CAT_654825', 'CAT_654823', 'Generic Smart Wearables', 'Wearable Technology > Generic Smart Wearables'),
	('CAT_654826', 'CAT_654823', 'Smart Clothing - Tops, Shirts & Jackets', 'Wearable Technology > Smart Clothing - Tops, Shirts & Jackets'),
	('CAT_654827', 'CAT_654823', 'Smart Clothing - Pants & Bottoms', 'Wearable Technology > Smart Clothing - Pants & Bottoms'),
	('CAT_654990', 'CAT_654823', 'Smart Healthcare Devices', 'Wearable Technology > Smart Healthcare Devices'),
	('CAT_654998', 'CAT_654823', 'Smart Pet Devices', 'Wearable Technology > Smart Pet Devices'),
	('CAT_655410', 'CAT_30658', 'Ink & Toner - Category Branch', 'Computers > Ink & Toner - Category Branch'),
	('CAT_656970', 'CAT_655410', 'Ink & Toner Subscription Plans', 'Computers > Ink & Toner - Category Branch > Ink & Toner Subscription Plans'),
	('CAT_659219', 'CAT_26337', 'Toys, Games & Collectibles', 'Toys, Sports & Recreation > Toys, Games & Collectibles'),
	('CAT_659225', 'CAT_26337', 'Sports & Recreation', 'Toys, Sports & Recreation > Sports & Recreation'),
	('CAT_659860', 'CAT_659225', 'Outdoor Recreational Games', 'Toys, Sports & Recreation > Sports & Recreation > Outdoor Recreational Games'),
	('CAT_659896', 'CAT_659225', 'Rec Room Games', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games'),
	('CAT_659900', 'CAT_659896', 'Rec Room Game Equipment', 'Toys, Sports & Recreation > Sports & Recreation > Rec Room Games > Rec Room Game Equipment'),
	('CAT_660196', '', 'Furniture - Category Branch', 'Furniture - Category Branch'),
	('CAT_660285', '', 'Pets', 'Pets'),
	('CAT_660292', 'CAT_27115', 'Other Appliances', 'Appliances > Other Appliances'),
	('CAT_660313', 'CAT_30837', 'Other Maternity Products', 'Baby & Kids > Other Maternity Products'),
	('CAT_660769', 'CAT_14', 'Other Camera & Camcorder Accessories', 'Cameras & Camcorders > Other Camera & Camcorder Accessories'),
	('CAT_660799', 'CAT_26336', 'Other Cell Phone Accessories', 'Cellular Phones > Other Cell Phone Accessories'),
	('CAT_660824', 'CAT_30658', 'Other Computer & Laptop Accessories', 'Computers > Other Computer & Laptop Accessories'),
	('CAT_660863', 'CAT_30840', 'Other Health & Beauty Products', 'Health, Beauty & Travel > Other Health & Beauty Products'),
	('CAT_660924', 'CAT_660196', 'Other Furniture', 'Furniture - Category Branch > Other Furniture'),
	('CAT_660943', '', 'Other Kitchen & Dining Products', 'Other Kitchen & Dining Products'),
	('CAT_660973', 'CAT_19', 'Other Portable Audio & Accessories', 'iPod & Portable Audio > Other Portable Audio & Accessories'),
	('CAT_660996', 'CAT_27237', 'Other Musical Instruments', 'Musical Instruments > Other Musical Instruments'),
	('CAT_661015', 'CAT_27603', 'Other Tools & Garden Products', 'Tools & Garden > Other Tools & Garden Products'),
	('CAT_670071', 'CAT_30840', 'Health & Fitness - Category Branch', 'Health, Beauty & Travel > Health & Fitness - Category Branch'),
	('CAT_670743', 'CAT_35719', 'Towels', 'Home & Furniture > Bathroom Accessories - Category Branch > Towels'),
	('CAT_671405', '', 'Household Cleaning- Category Branch', 'Household Cleaning- Category Branch'),
	('CAT_671406', 'CAT_671405', 'Household Cleaning Tools', 'Household Cleaning- Category Branch > Household Cleaning Tools'),
	('CAT_682461', 'CAT_30840', 'Skin Care & Cosmetics - Category Branch', 'Health, Beauty & Travel > Skin Care & Cosmetics - Category Branch'),
	('CAT_682462', 'CAT_682461', 'Skin Care', 'Health, Beauty & Travel > Skin Care & Cosmetics - Category Branch > Skin Care'),
	('CAT_682541', 'CAT_682461', 'Bath & Body', 'Health, Beauty & Travel > Skin Care & Cosmetics - Category Branch > Bath & Body'),
	('CAT_690294', 'CAT_15', 'Video Game Controllers', 'Gaming > Video Game Controllers'),
	('CAT_7671', 'CAT_22', 'Cables & Adapters', 'Multi-Dept and Generic > Cables & Adapters'),
	('CAT_7673', 'CAT_31177', 'Paper', 'Office Supplies > Paper'),
	('CAT_7675', 'CAT_30658', 'Computer Speakers', 'Computers > Computer Speakers'),
	('CAT_7686', 'CAT_27115', 'Air Conditioners', 'Appliances > Air Conditioners'),
	('CAT_7687', 'CAT_27115', 'BBQs, Smokers & Outdoor Cooking', 'Appliances > BBQs, Smokers & Outdoor Cooking'),
	('CAT_7697', 'CAT_30658', 'Software', 'Computers > Software'),
	('CAT_804879', 'CAT_14', 'Card Readers & Writers', 'Cameras & Camcorders > Card Readers & Writers'),
	('CAT_810985', 'CAT_682461', 'Scents & Fragrances', 'Health, Beauty & Travel > Skin Care & Cosmetics - Category Branch > Scents & Fragrances'),
	('CAT_815685', 'CAT_670071', 'Ellipticals & Rowing Machines', 'Health, Beauty & Travel > Health & Fitness - Category Branch > Ellipticals & Rowing Machines'),
	('CAT_823786', 'CAT_31441', 'Glassware & Drinkware', 'Dinnerware & Glassware - Category Branch > Glassware & Drinkware'),
	('CAT_823803', 'CAT_31443', 'Cookware & Ovenware Sets', 'Cookware & Bakeware - Category Branch > Cookware & Ovenware Sets'),
	('CAT_829711', 'CAT_22210', 'Clocks', 'Home Decor - Category Branch > Clocks'),
	('CAT_9', '', 'Car, Marine & GPS', 'Car, Marine & GPS'),
	('CAT_908115', 'CAT_11', 'Turntables', 'Home Theatre > Turntables'),
	('CAT_938329', '', 'Pools & Hot Tubs', 'Pools & Hot Tubs'),
	('CAT_938332', '', 'Saunas', 'Saunas'),
	('CAT_938334', 'CAT_659219', 'Anatomical and Science Models', 'Toys, Sports & Recreation > Toys, Games & Collectibles > Anatomical and Science Models'),
	('CAT_968928', 'CAT_11', 'Antennas', 'Home Theatre > Antennas'),
	('CAT_971511', 'CAT_27237', 'Guitar Stings', 'Musical Instruments > Guitar Stings');
/*!40000 ALTER TABLE `bestbuy_category` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
