<?php

$bestbuyCate = [
    [ 'code' => "CAT_27115", 'name' => 'Appliances', 'children' => [
        [ 'code' => "CAT_7686", 'name' => 'Air Conditioners' ],
        [ 'code' => "CAT_25876", 'name' => 'Air Purifier Filters' ],
        [ 'code' => "CAT_10837", 'name' => 'Air Purifiers' ],
        [ 'code' => "CAT_19542", 'name' => 'Appliances Accessories' ],
        [ 'code' => "CAT_17131", 'name' => 'Bar Fridges' ],
        [ 'code' => "CAT_7687", 'name' => 'BBQs, Smokers & Outdoor Cooking' ],
        [ 'code' => "CAT_35734", 'name' => 'Blenders' ],
        [ 'code' => "CAT_10851", 'name' => 'Bread Makers' ],
        [ 'code' => "CAT_1810", 'name' => 'Canister & Upright Vacuums' ],
        [ 'code' => "CAT_10859", 'name' => 'Coffee Grinders' ],
        [ 'code' => "CAT_29216", 'name' => 'Coffee Makers & Espresso Machines' ],
        [ 'code' => "CAT_29740", 'name' => 'Coffee, Tea, Other Beverages' ],
        [ 'code' => "CAT_10845", 'name' => 'Cookers & Steamers' ],
        [ 'code' => "CAT_10848", 'name' => 'Deep Fryers' ],
        [ 'code' => "CAT_10832", 'name' => 'Dehumidifiers' ],
        [ 'code' => "CAT_1951", 'name' => 'Dishwashers' ],
        [ 'code' => "CAT_1950", 'name' => 'Dryers' ],
        [ 'code' => "CAT_37205", 'name' => 'Dual Fuel Ranges' ],
        [ 'code' => "CAT_10872", 'name' => 'Electric & Gas Cooktops' ],
        [ 'code' => "CAT_1952", 'name' => 'Electric Ranges' ],
        [ 'code' => "CAT_30821", 'name' => 'Fans' ],
        [ 'code' => "CAT_10844", 'name' => 'Food Processor & Choppers' ],
        [ 'code' => "CAT_1954", 'name' => 'Freezers', 'children' => [
            [ 'code' => "CAT_313858", 'name' => 'Freezers' ],
        ]],
        [ 'code' => "CAT_10744", 'name' => 'Gas Ranges' ],
        [ 'code' => "CAT_30822", 'name' => 'Heater & Fireplace Parts' ],
        [ 'code' => "CAT_32872", 'name' => 'Heaters & Fireplaces' ],
        [ 'code' => "CAT_10831", 'name' => 'Humidifiers' ],
        [ 'code' => "CAT_10852", 'name' => 'Indoor Grills' ],
        [ 'code' => "CAT_27586", 'name' => 'Irons & Steamers' ],
        [ 'code' => "CAT_27123", 'name' => 'Juicers' ],
        [ 'code' => "CAT_33539", 'name' => 'Kettles & Hot Water Dispensers' ],
        [ 'code' => "CAT_30281", 'name' => 'Kitchen Scales' ],
        [ 'code' => "CAT_27136", 'name' => 'Microwaves' ],
        [ 'code' => "CAT_33542", 'name' => 'Mixers' ],
        [ 'code' => "CAT_660292", 'name' => 'Other Appliances' ],
        [ 'code' => "CAT_10861", 'name' => 'Popcorn Makers' ],
        [ 'code' => "CAT_19561", 'name' => 'Range Hoods' ],
        [ 'code' => "CAT_1953", 'name' => 'Refrigerators' ],
        [ 'code' => "CAT_30577", 'name' => 'Sewing Machines' ],
        [ 'code' => "CAT_34823", 'name' => 'Soda Makers & Accessories' ],
        [ 'code' => "CAT_33182", 'name' => 'Specialty Vacuums & Floor Care' ],
        [ 'code' => "CAT_10742", 'name' => 'Stacked Laundry Pairs' ],
        [ 'code' => "CAT_10843", 'name' => 'Toaster Ovens' ],
        [ 'code' => "CAT_10842", 'name' => 'Toasters' ],
        [ 'code' => "CAT_10735", 'name' => 'Wall Ovens' ],
        [ 'code' => "CAT_1949", 'name' => 'Washers' ],
        [ 'code' => "CAT_27595", 'name' => 'Water Filters' ],
        [ 'code' => "CAT_10860", 'name' => 'Water Purifiers & Coolers' ],
        [ 'code' => "CAT_23875", 'name' => 'Wine Cellars & Coolers' ],
    ]],

    [ 'code' => "CAT_30837", 'name' => 'Baby & Kids', 'children' => [
        [ 'code' => "CAT_32803", 'name' => '(delete)Baby Travel Beds' ],
        [ 'code' => "CAT_33537", 'name' => 'Baby & Child Clothes' ],
        [ 'code' => "CAT_1159939", 'name' => 'Baby & Child Fashion Accessories' ],
        [ 'code' => "CAT_34807", 'name' => 'Baby & Child Shoes' ],
        [ 'code' => "CAT_29502", 'name' => 'Baby Bath Tubs' ],
        [ 'code' => "CAT_32865", 'name' => 'Baby Bouncers' ],
        [ 'code' => "CAT_32858", 'name' => 'Baby Car Seats & Booster Seats' ],
        [ 'code' => "CAT_32859", 'name' => 'Baby Carriers & Slings' ],
        [ 'code' => "CAT_32810", 'name' => 'Baby Cribs & Bassinets' ],
        [ 'code' => "CAT_32860", 'name' => 'Baby Diaper Bags' ],
        [ 'code' => "CAT_32866", 'name' => 'Baby Diapers' ],
        [ 'code' => "CAT_35724", 'name' => 'Baby Feeding' ],
        [ 'code' => "CAT_32873", 'name' => 'Baby Monitors' ],
        [ 'code' => "CAT_32804", 'name' => 'Baby Playpens, Playards & Travel Beds' ],
        [ 'code' => "CAT_32867", 'name' => 'Baby Potties & Accessories' ],
        [ 'code' => "CAT_1159945", 'name' => 'Baby Proofing & Safe Sleeping' ],
        [ 'code' => "CAT_29501", 'name' => 'Baby Safety Gates' ],
        [ 'code' => "CAT_32861", 'name' => 'Baby Stroller & Car Seat Accessories' ],
        [ 'code' => "CAT_37136", 'name' => 'Baby Stroller & Car Seat Combo' ],
        [ 'code' => "CAT_32512", 'name' => 'Baby Strollers' ],
        [ 'code' => "CAT_35725", 'name' => 'Baby Toys' ],
        [ 'code' => "CAT_32515", 'name' => 'Breast Pumps' ],
        [ 'code' => "CAT_1159937", 'name' => 'Crib Bedding & Accessories' ],
        [ 'code' => "CAT_32831", 'name' => 'Food Mills' ],
        [ 'code' => "CAT_33611", 'name' => 'Gliders' ],
        [ 'code' => "CAT_35733", 'name' => 'High Chairs & Booster Seats' ],
        [ 'code' => "CAT_35731", 'name' => 'Maternity Clothes & Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_37328", 'name' => 'Maternity Bottoms' ],
            [ 'code' => "CAT_37212", 'name' => 'Maternity Dresses' ],
            [ 'code' => "CAT_37329", 'name' => 'Maternity Sleepwear' ],
            [ 'code' => "CAT_37211", 'name' => 'Maternity Swimwear & Underwear' ],
            [ 'code' => "CAT_37209", 'name' => 'Maternity Tops' ],
        ]],
        [ 'code' => "CAT_1159940", 'name' => 'Nursery Decor' ],
        [ 'code' => "CAT_35718", 'name' => 'Nursery Furniture-Other' ],
        [ 'code' => "CAT_32826", 'name' => 'Nursing Accessories' ],
        [ 'code' => "CAT_32863", 'name' => 'Other Baby Products' ],
        [ 'code' => "CAT_660313", 'name' => 'Other Maternity Products' ],
    ]],

    [ 'code' => "CAT_14", 'name' => 'Cameras & Camcorders', 'children' => [
        [ 'code' => "CAT_30860", 'name' => 'Batteries & Chargers' ],
        [ 'code' => "CAT_25713", 'name' => 'Camcorders' ],
        [ 'code' => "CAT_25794", 'name' => 'Camera Lenses - Category Branch', 'children' => [
            [ 'code' => "CAT_328641", 'name' => 'Camera Lenses' ],
        ]],
        [ 'code' => "CAT_804879", 'name' => 'Card Readers & Writers' ],
        [ 'code' => "CAT_30859", 'name' => 'Cases, Bags & Straps' ],
        [ 'code' => "CAT_1127", 'name' => 'Compact Digital Cameras' ],
        [ 'code' => "CAT_23753", 'name' => 'Digital Memory' ],
        [ 'code' => "CAT_25855", 'name' => 'Digital Photo Frames' ],
        [ 'code' => "CAT_23773", 'name' => 'DSLR Cameras' ],
        [ 'code' => "CAT_29283", 'name' => 'Flashes' ],
        [ 'code' => "CAT_22569", 'name' => 'Lens Filters' ],
        [ 'code' => "CAT_660769", 'name' => 'Other Camera & Camcorder Accessories' ],
        [ 'code' => "CAT_30861", 'name' => 'Tripods & Monopods' ],
    ]],

    [ 'code' => "CAT_9", 'name' => 'Car, Marine & GPS', 'children' => [
        [ 'code' => "CAT_482331", 'name' => 'Auto Parts' ],
        [ 'code' => "CAT_26299", 'name' => 'Back Up Cameras & Dash Cams' ],
        [ 'code' => "CAT_24853", 'name' => 'Car &  Motorcycle GPS' ],
        [ 'code' => "CAT_11031", 'name' => 'Car Amplifiers - 1 & 2 Channels' ],
        [ 'code' => "CAT_11032", 'name' => 'Car Amplifiers - 4+ Channels' ],
        [ 'code' => "CAT_482214", 'name' => 'Car Dash Trim Kits' ],
        [ 'code' => "CAT_12038", 'name' => 'Car Decks - Double DIN' ],
        [ 'code' => "CAT_1101", 'name' => 'Car Decks - Single DIN' ],
        [ 'code' => "CAT_479916", 'name' => 'Car Decks - Vehicle Specific' ],
        [ 'code' => "CAT_11035", 'name' => 'Car Equalizers & Crossovers' ],
        [ 'code' => "CAT_32016", 'name' => 'Car Floor Mats' ],
        [ 'code' => "CAT_12037", 'name' => 'Car GPS Navigation Modules' ],
        [ 'code' => "CAT_12036", 'name' => 'Car Multimedia Packages' ],
        [ 'code' => "CAT_14503", 'name' => 'Car Security & Starters' ],
        [ 'code' => "CAT_1104", 'name' => 'Car Speakers' ],
        [ 'code' => "CAT_11062", 'name' => 'Car Subwoofer Enclosures' ],
        [ 'code' => "CAT_481936", 'name' => 'Car Subwoofer Enclosures - Vehicle-Specific' ],
        [ 'code' => "CAT_1105", 'name' => 'Car Subwoofers' ],
        [ 'code' => "CAT_12039", 'name' => 'Car Video Monitors' ],
        [ 'code' => "CAT_32878", 'name' => 'Car Window Tint Films' ],
        [ 'code' => "CAT_32857", 'name' => 'Cycling GPS & Bike Computers' ],
        [ 'code' => "CAT_23116", 'name' => 'Marine Amplifiers' ],
        [ 'code' => "CAT_25835", 'name' => 'Marine GPS' ],
        [ 'code' => "CAT_23115", 'name' => 'Marine Speakers' ],
        [ 'code' => "CAT_32877", 'name' => 'Other Automotive Accessories' ],
        [ 'code' => "CAT_25836", 'name' => 'Outdoor GPS' ],
        [ 'code' => "CAT_24635", 'name' => 'Replacement Remotes' ],
    ]],

    [ 'code' => "CAT_26336", 'name' => 'Cellular Phones', 'children' => [
        [ 'code' => "CAT_29095", 'name' => 'BlackBerry Power & Cables' ],
        [ 'code' => "CAT_25938", 'name' => 'Bluetooth Handsfree Headsets' ],
        [ 'code' => "CAT_25940", 'name' => 'Bluetooth Speakerphones' ],
        [ 'code' => "CAT_30177", 'name' => 'Cell Phone Cases' ],
        [ 'code' => "CAT_496383", 'name' => 'Cell Phone Signal Boosters' ],
        [ 'code' => "CAT_29000", 'name' => 'Cell Phones & Smartphones' ],
        [ 'code' => "CAT_11111", 'name' => 'Cellular Batteries' ],
        [ 'code' => "CAT_32083", 'name' => 'Chargers & Power Adapters' ],
        [ 'code' => "CAT_25930", 'name' => 'iPhone Power & Cables' ],
        [ 'code' => "CAT_660799", 'name' => 'Other Cell Phone Accessories' ],
    ]],

    [ 'code' => "CAT_30658", 'name' => 'Computers', 'children' => [
        [ 'code' => "CAT_34908", 'name' => '3D Printer Accessories' ],
        [ 'code' => "CAT_34907", 'name' => '3D Printer Cartridges' ],
        [ 'code' => "CAT_34906", 'name' => '3D Printers' ],
        [ 'code' => "CAT_10781", 'name' => 'All-in-One Inkjet Printers' ],
        [ 'code' => "CAT_26455", 'name' => 'All-in-One Laser Printers' ],
        [ 'code' => "CAT_23033", 'name' => 'Blank Discs, Cases & Accessories' ],
        [ 'code' => "CAT_23278", 'name' => 'Computer Battery Back Up' ],
        [ 'code' => "CAT_10476", 'name' => 'Computer Cases' ],
        [ 'code' => "CAT_1076", 'name' => 'Computer Memory' ],
        [ 'code' => "CAT_7675", 'name' => 'Computer Speakers' ],
        [ 'code' => "CAT_1003", 'name' => 'Desktop Computers' ],
        [ 'code' => "CAT_1082", 'name' => 'DVD Drives - Category Branch' , 'children' => [
            [ 'code' => "CAT_26395", 'name' => 'Blu-ray Drives' ],
            [ 'code' => "CAT_314719", 'name' => 'DVD Drives' ],
        ]],
        [ 'code' => "CAT_28462", 'name' => 'eReader Cases & Protectors' ],
        [ 'code' => "CAT_33175", 'name' => 'eReaders' ],
        [ 'code' => "CAT_10776", 'name' => 'Fax Machines' ],
        [ 'code' => "CAT_14262", 'name' => 'Gamepads, Joysticks & Aviation Controls (for PC only)' ],
        [ 'code' => "CAT_33070", 'name' => 'Gaming Chairs' ],
        [ 'code' => "CAT_33179", 'name' => 'Graphics Tablets & Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_314700", 'name' => 'Graphics Tablets & Accessories' ],
            [ 'code' => "CAT_27320", 'name' => 'Mice' ],
        ]],
        [ 'code' => "CAT_1084", 'name' => 'Hard Drives' ],
        [ 'code' => "CAT_655410", 'name' => 'Ink & Toner - Category Branch', 'children' => [
            [ 'code' => "CAT_1171", 'name' => 'Ink & Toner Cartridges' ],
            [ 'code' => "CAT_656970", 'name' => 'Ink & Toner Subscription Plans' ],
        ]],
        [ 'code' => "CAT_30664", 'name' => 'iPad & Tablet Accessories' ],
        [ 'code' => "CAT_30663", 'name' => 'iPad & Tablet Cases, Screen Protectors & Keyboards' ],
        [ 'code' => "CAT_14263", 'name' => 'Joysticks & Aviation Controls (for PC only)' ],
        [ 'code' => "CAT_14266", 'name' => 'Keyboard and Mouse Combos' ],
        [ 'code' => "CAT_33180", 'name' => 'Keyboards' ],
        [ 'code' => "CAT_25595", 'name' => 'Laptop Batteries' ],
        [ 'code' => "CAT_29437", 'name' => 'Laptop Carrying Cases & Bags' ],
        [ 'code' => "CAT_1002", 'name' => 'Laptops' ],
        [ 'code' => "CAT_29556", 'name' => 'Mobile Internet Hubs & Sticks' ],
        [ 'code' => "CAT_1006", 'name' => 'Monitors' ],
        [ 'code' => "CAT_10481", 'name' => 'Motherboards' ],
        [ 'code' => "CAT_10494", 'name' => 'Network Cables' ],
        [ 'code' => "CAT_19997", 'name' => 'Network Cards' ],
        [ 'code' => "CAT_660824", 'name' => 'Other Computer & Laptop Accessories' ],
        [ 'code' => "CAT_30057", 'name' => 'Other Specialty Printers' ],
        [ 'code' => "CAT_10482", 'name' => 'Power Supplies' ],
        [ 'code' => "CAT_19996", 'name' => 'Print Servers' ],
        [ 'code' => "CAT_10483", 'name' => 'Processors' ],
        [ 'code' => "CAT_1544", 'name' => 'Projectors' ],
        [ 'code' => "CAT_29588", 'name' => 'Range Extenders & Powerline Networking' ],
        [ 'code' => "CAT_33123", 'name' => 'SATA & IDE Controller Cards' ],
        [ 'code' => "CAT_1012", 'name' => 'Scanners' ],
        [ 'code' => "CAT_33122", 'name' => 'Serial & Parallel Port Controller Cards' ],
        [ 'code' => "CAT_10492", 'name' => 'Single Function Inkjet Printers' ],
        [ 'code' => "CAT_10233", 'name' => 'Single Function Laser Printers' ],
        [ 'code' => "CAT_7697", 'name' => 'Software' ],
        [ 'code' => "CAT_10499", 'name' => 'Sound Cards' ],
        [ 'code' => "CAT_10446", 'name' => 'Surge Protectors' ],
        [ 'code' => "CAT_29958", 'name' => 'Tablets - Category Branch', 'children' => [
            [ 'code' => "CAT_28777", 'name' => 'Apple iPad' ],
            [ 'code' => "CAT_314802", 'name' => 'Tablets' ],
        ]],
        [ 'code' => "CAT_451680", 'name' => 'Travel Power Adapters' ],
        [ 'code' => "CAT_25615", 'name' => 'TV Tuners' ],
        [ 'code' => "CAT_11288", 'name' => 'USB & FireWire Cards & Hubs' ],
        [ 'code' => "CAT_23813", 'name' => 'USB Drives' ],
        [ 'code' => "CAT_10526", 'name' => 'Video Capture & Editing' ],
        [ 'code' => "CAT_25617", 'name' => 'Video Cards' ],
        [ 'code' => "CAT_23853", 'name' => 'Webcams' ],
        [ 'code' => "CAT_10488", 'name' => 'Wired Hubs & Switches' ],
        [ 'code' => "CAT_10489", 'name' => 'Wired Modems' ],
        [ 'code' => "CAT_10495", 'name' => 'Wired Routers' ],
        [ 'code' => "CAT_19994", 'name' => 'Wireless Routers' ],
        [ 'code' => "CAT_25614", 'name' => 'Wireless USB Adapters' ],
    ]],

    [ 'code' => "CAT_15", 'name' => 'Gaming', 'children' => [
        [ 'code' => "CAT_1034", 'name' => 'PC Games' ],
        [ 'code' => "CAT_26378", 'name' => 'Video Game Accessories' ],
        [ 'code' => "CAT_29103", 'name' => 'Video Game Consoles' ],
        [ 'code' => "CAT_690294", 'name' => 'Video Game Controllers' ],
        [ 'code' => "CAT_23353", 'name' => 'Video Games' ],
    ]],

    [ 'code' => "CAT_29001", 'name' => 'Geek Squad' ],
    [ 'code' => "CAT_17", 'name' => 'Gift Cards', 'children' => [
        [ 'code' => "CAT_22082", 'name' => 'Gift Cards', 'children' => [
            [ 'code' => "CAT_22083", 'name' => 'Future Shop Gift Cards' ],
        ]],
    ]],

    [ 'code' => "CAT_30840", 'name' => 'Health, Beauty & Travel', 'children' => [
        [ 'code' => "CAT_27327", 'name' => 'Curling Irons' ],
        [ 'code' => "CAT_27425", 'name' => 'Electric Toothbrushes' ],
        [ 'code' => "CAT_31942", 'name' => 'Fashion Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_37201", 'name' => 'Cufflinks, Pins, Brooches' ],
            [ 'code' => "CAT_33527", 'name' => 'Eyewear - Category Branch', 'children' => [
                [ 'code' => "CAT_314829", 'name' => 'Eyewear' ],
                [ 'code' => "CAT_33161", 'name' => 'Sunglasses' ],
            ]],
            [ 'code' => "CAT_32838", 'name' => 'Lunch Bags & Boxes' ],
            [ 'code' => "CAT_32006", 'name' => 'More Fashion Accessories' ],
            [ 'code' => "CAT_32001", 'name' => 'Scarves' ],
        ]],
        [ 'code' => "CAT_33569", 'name' => 'Floss' ],
        [ 'code' => "CAT_32870", 'name' => 'Hair Care' ],
        [ 'code' => "CAT_27329", 'name' => 'Hair Dryers' ],
        [ 'code' => "CAT_27328", 'name' => 'Hair Straighteners' ],
        [ 'code' => "CAT_670071", 'name' => 'Health & Fitness - Category Branch', 'children' => [
            [ 'code' => "CAT_815685", 'name' => 'Ellipticals & Rowing Machines' ],
            [ 'code' => "CAT_35715", 'name' => 'Exercise Bikes' ],
            [ 'code' => "CAT_27385", 'name' => 'Health & Fitness' ],
            [ 'code' => "CAT_27398", 'name' => 'Heart Rate Monitors' ],
            [ 'code' => "CAT_27400", 'name' => 'Treadmills' ],
            [ 'code' => "CAT_31990", 'name' => 'Yoga & Stability Balls' ],
            [ 'code' => "CAT_27596", 'name' => 'Yoga Mats' ],
        ]],
        [ 'code' => "CAT_35585", 'name' => 'Jewelry - Category Branch', 'children' => [
            [ 'code' => "CAT_32005", 'name' => 'Bracelets, Bangles & Cuffs' ],
            [ 'code' => "CAT_32003", 'name' => 'Earrings' ],
            [ 'code' => "CAT_314831", 'name' => 'Jewelry' ],
            [ 'code' => "CAT_35611", 'name' => 'Jewelry Sets' ],
            [ 'code' => "CAT_32004", 'name' => 'Necklaces' ],
            [ 'code' => "CAT_32002", 'name' => 'Rings' ],
        ]],
        [ 'code' => "CAT_35581", 'name' => 'Jewelry Boxes' ],
        [ 'code' => "CAT_1653054", 'name' => 'Luggage & Bags Temp - Category Branch' ],
        [ 'code' => "CAT_31198", 'name' => 'Luggage - Category Branch', 'children' => [
            [ 'code' => "CAT_27000", 'name' => 'Backpacks' ],
            [ 'code' => "CAT_32007", 'name' => 'Handbags & Purses' ],
            [ 'code' => "CAT_313874", 'name' => 'Luggage' ],
            [ 'code' => "CAT_33178", 'name' => 'Luggage Sets' ],
            [ 'code' => "CAT_37937", 'name' => 'Wallets & Clutches' ],
        ]],
        [ 'code' => "CAT_32936", 'name' => 'Manual Razors & Blades' ],
        [ 'code' => "CAT_32937", 'name' => 'Manual Toothbrushes' ],
        [ 'code' => "CAT_32916", 'name' => 'Massage Chairs' ],
        [ 'code' => "CAT_32875", 'name' => 'Medical Thermometers' ],
        [ 'code' => "CAT_33570", 'name' => 'Mouthwash' ],
        [ 'code' => "CAT_660863", 'name' => 'Other Health & Beauty Products' ],
        [ 'code' => "CAT_456160", 'name' => 'Protein Shakes & Health Food' ],
        [ 'code' => "CAT_32966", 'name' => 'Replacement Brush Heads' ],
        [ 'code' => "CAT_32874", 'name' => 'Scales' ],
        [ 'code' => "CAT_34806", 'name' => 'Sexual Wellness' ],
        [ 'code' => "CAT_27317", 'name' => 'Shavers and Groomers' ],
        [ 'code' => "CAT_682461", 'name' => 'Skin Care & Cosmetics - Category Branch', 'children' => [
            [ 'code' => "CAT_682541", 'name' => 'Bath & Body' ],
            [ 'code' => "CAT_32869", 'name' => 'Cosmetics & Makeup' ],
            [ 'code' => "CAT_810985", 'name' => 'Scents & Fragrances' ],
            [ 'code' => "CAT_682462", 'name' => 'Skin Care' ],
        ]],
        [ 'code' => "CAT_30844", 'name' => 'Spas & Getaway Experience Gifts' ],
        [ 'code' => "CAT_33066", 'name' => 'Teeth Whitening Strips' ],
        [ 'code' => "CAT_33159", 'name' => 'Toothpaste' ],
        [ 'code' => "CAT_32871", 'name' => 'Umbrellas and Parasols' ],
        [ 'code' => "CAT_26380", 'name' => 'Vitamins & Supplements' ],
        [ 'code' => "CAT_32876", 'name' => 'Watches' ],
    ]],

    [ 'code' => "CAT_30839", 'name' => 'Home & Furniture', 'children' => [
        [ 'code' => "CAT_31438", 'name' => 'Barbecue Parts & Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_31448", 'name' => 'Barbecue Accessories Sets' ],
            [ 'code' => "CAT_314933", 'name' => 'Barbecue Parts & Accessories' ],
        ]],
        [ 'code' => "CAT_35719", 'name' => 'Bathroom Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_37131", 'name' => 'Bath Hooks & Holders' ],
            [ 'code' => "CAT_328963", 'name' => 'Bathroom Accessories' ],
            [ 'code' => "CAT_670743", 'name' => 'Towels' ],
        ]],
    ]],

    [ 'code' => "CAT_37129", 'name' => 'Bathroom Sink Faucets' ],
    [ 'code' => "CAT_1295098", 'name' => 'Bed Sheets' ],
    [ 'code' => "CAT_29637", 'name' => 'Bedding & Linens' ],
    [ 'code' => "CAT_31995", 'name' => 'Candles' ],
    [ 'code' => "CAT_31443", 'name' => 'Cookware & Bakeware - Category Branch', 'children' => [
        [ 'code' => "CAT_314930", 'name' => 'Bakeware - Individual Pieces' ],
        [ 'code' => "CAT_31463", 'name' => 'Bakeware Sets' ],
        [ 'code' => "CAT_31442", 'name' => 'Cookware & Ovenware - Individual Pieces' ],
        [ 'code' => "CAT_823803", 'name' => 'Cookware & Ovenware Sets' ],
    ]],

    [ 'code' => "CAT_33528", 'name' => 'Decorative Cushion Covers' ],
    [ 'code' => "CAT_31441", 'name' => 'Dinnerware & Glassware - Category Branch', 'children' => [
        [ 'code' => "CAT_314941", 'name' => 'Dinnerware & Serveware - Individual Pieces' ],
        [ 'code' => "CAT_31457", 'name' => 'Dinnerware & Serveware Sets' ],
        [ 'code' => "CAT_823786", 'name' => 'Glassware & Drinkware' ],
    ]],

    [ 'code' => "CAT_31451", 'name' => 'Flatware' ],
    [ 'code' => "CAT_32883", 'name' => 'Floor Sweepers & Mops - Category Branch', 'children' => [
        [ 'code' => "CAT_33068", 'name' => 'Sweeper & Duster Refills & Accessories' ],
        [ 'code' => "CAT_33067", 'name' => 'Sweepers, Dusters & Mops' ],
    ]],

    [ 'code' => "CAT_660196", 'name' => 'Furniture - Category Branch', 'children' => [
        [ 'code' => "CAT_609281", 'name' => 'Bedroom Sets' ],
        [ 'code' => "CAT_35729", 'name' => 'Beds & Bed Frames' ],
        [ 'code' => "CAT_615197", 'name' => 'Bookcases & Shelving' ],
        [ 'code' => "CAT_33549", 'name' => 'Dining Sets' ],
        [ 'code' => "CAT_32000", 'name' => 'Headboards & Footboards' ],
        [ 'code' => "CAT_33548", 'name' => 'Kitchen & Dining Room Chairs' ],
        [ 'code' => "CAT_33547", 'name' => 'Kitchen & Dining Room Tables' ],
        [ 'code' => "CAT_33544", 'name' => 'Living Room Chairs' ],
        [ 'code' => "CAT_609229", 'name' => 'Living Room Sets' ],
        [ 'code' => "CAT_33540", 'name' => 'Living Room Tables' ],
        [ 'code' => "CAT_34822", 'name' => 'Mattress Foundations' ],
        [ 'code' => "CAT_34821", 'name' => 'Mattresses & Mattress Toppers' ],
        [ 'code' => "CAT_32742", 'name' => 'Media Storage' ],
        [ 'code' => "CAT_328906", 'name' => 'More Bedroom Furniture - Category Branch' ],
        [ 'code' => "CAT_32509", 'name' => 'More Kitchen & Dining Furniture - Category Branch' ],
        [ 'code' => "CAT_33553", 'name' => 'Office Chairs' ],
        [ 'code' => "CAT_31946", 'name' => 'Office Desks & Sets' ],
        [ 'code' => "CAT_33551", 'name' => 'Office Storage Cabinets & Hutches' ],
        [ 'code' => "CAT_660924", 'name' => 'Other Furniture' ],
        [ 'code' => "CAT_33546", 'name' => 'Ottomans & Living Room Benches' ],
        [ 'code' => "CAT_24253", 'name' => 'Outdoor Furniture Covers' ],
        [ 'code' => "CAT_33535", 'name' => 'Patio Chairs' ],
        [ 'code' => "CAT_31943", 'name' => 'Patio Cushions & More - Category Branch' ],
        [ 'code' => "CAT_33536", 'name' => 'Patio Tables' ],
        [ 'code' => "CAT_33550", 'name' => 'Patio Umbrellas' ],
        [ 'code' => "CAT_33545", 'name' => 'Sofas, Sectionals & Futons - Category Branch' ],
    ]],

    [ 'code' => "CAT_27383", 'name' => 'Home Automation & Accessories - Category Branch', 'children' => [
        [ 'code' => "CAT_640692", 'name' => 'Energy & Resource Management' ],
        [ 'code' => "CAT_314919", 'name' => 'Home Automation Accessories' ],
        [ 'code' => "CAT_25944", 'name' => 'Home Automation Modules' ],
        [ 'code' => "CAT_37144", 'name' => 'Smart Home Controls & Access' ],
        [ 'code' => "CAT_37140", 'name' => 'Smart Lights & Controls' ],
    ]],

    [ 'code' => "CAT_22210", 'name' => 'Home Decor - Category Branch', 'children' => [
        [ 'code' => "CAT_10011", 'name' => 'Art & Wall Décor' ],
        [ 'code' => "CAT_829711", 'name' => 'Clocks' ],
        [ 'code' => "CAT_11008", 'name' => 'Fireplaces' ],
        [ 'code' => "CAT_314924", 'name' => 'Home Decor' ],
        [ 'code' => "CAT_32827", 'name' => 'Posters' ],
    ]],

    [ 'code' => "CAT_35673", 'name' => 'Home Security Sensors, Alarms and Monitors' ],
    [ 'code' => "CAT_671405", 'name' => 'Household Cleaning- Category Branch', 'children' => [
        [ 'code' => "CAT_35714", 'name' => 'Household Cleaning Agents' ],
        [ 'code' => "CAT_671406", 'name' => 'Household Cleaning Tools' ],
    ]],

    [ 'code' => "CAT_27316", 'name' => 'Kitchen Gadgets & Utensils - Category Branch', 'children' => [
        [ 'code' => "CAT_10857", 'name' => 'Can Openers' ],
        [ 'code' => "CAT_314937", 'name' => 'Kitchen & Dining Accessories' ],
    ]],

    [ 'code' => "CAT_31437", 'name' => 'Kitchen Knives - Category Branch', 'children' => [
        [ 'code' => "CAT_10858", 'name' => 'Electric Knives' ],
        [ 'code' => "CAT_31444", 'name' => 'Kitchen Knife Sets' ],
        [ 'code' => "CAT_31445", 'name' => 'Kitchen Knives - Individual Pieces' ],
        [ 'code' => "CAT_31446", 'name' => 'Knife Blocks' ],
        [ 'code' => "CAT_328904", 'name' => 'Knives & Cutlery' ],
    ]],

    [ 'code' => "CAT_32884", 'name' => 'Lamps & Lighting' ],
    [ 'code' => "CAT_33534", 'name' => 'Lawn Mower Parts - Category Branch', 'children' => [
        [ 'code' => "CAT_33636", 'name' => 'Lawn Mower Parts' ],
        [ 'code' => "CAT_35787", 'name' => 'Snow Blower Parts' ],
    ]],

    [ 'code' => "CAT_33532", 'name' => 'Lawn Mowers' ],
    [ 'code' => "CAT_25756", 'name' => 'More Smart Home & Security' ],
    [ 'code' => "CAT_660943", 'name' => 'Other Kitchen & Dining Products' ],
    [ 'code' => "CAT_32517", 'name' => 'Pillows & Cushions' ],
    [ 'code' => "CAT_938329", 'name' => 'Pools & Hot Tubs' ],
    [ 'code' => "CAT_938332", 'name' => 'Saunas' ],
    [ 'code' => "CAT_35671", 'name' => 'Security Camera Accessories' ],
    [ 'code' => "CAT_37130", 'name' => 'Shower & Bath Faucets' ],
    [ 'code' => "CAT_31950", 'name' => 'Shower Heads & Hand Showers' ],
    [ 'code' => "CAT_35726", 'name' => 'Surveillance Receiver & DVRs' ],
    [ 'code' => "CAT_35586", 'name' => 'Surveillance Systems & Cameras' ],

    [ 'code' => "CAT_11", 'name' => 'Home Theatre', 'children' => [
        [ 'code' => "CAT_968928", 'name' => 'Antennas' ],
        [ 'code' => "CAT_25320", 'name' => 'Blu-ray & DVD Players - Category Branch', 'children' => [
            [ 'code' => "CAT_29037", 'name' => 'Blu-ray & DVD Players' ],
            [ 'code' => "CAT_28138", 'name' => 'Portable Blu-ray & DVD Players' ],
        ]],
        [ 'code' => "CAT_29877", 'name' => 'Combination TVs' ],
        [ 'code' => "CAT_2002", 'name' => 'Digital Cable - Category Branch', 'children' => [
            [ 'code' => "CAT_315699", 'name' => 'Digital Cable' ],
            [ 'code' => "CAT_24996", 'name' => 'Digital Cable Boxes' ],
        ]],
        [ 'code' => "CAT_1042", 'name' => 'DVD Players - Category Branch - to be deleted', 'children' => [
            [ 'code' => "CAT_10561", 'name' => 'DVD Players - to be deleted' ],
            [ 'code' => "CAT_10568", 'name' => 'Portable DVD Players - to be deleted' ],
        ]],
        [ 'code' => "CAT_24854", 'name' => 'DVD Video Recorders' ],
        [ 'code' => "CAT_25881", 'name' => 'Home Audio Adapters' ],
        [ 'code' => "CAT_1047", 'name' => 'Home Speakers - Category Branch', 'children' => [
            [ 'code' => "CAT_315694", 'name' => 'Home Speakers' ],
            [ 'code' => "CAT_10554", 'name' => 'Subwoofers' ],
            [ 'code' => "CAT_14700", 'name' => 'Surround Speaker Packages (Speakers & Subwoofer Only)' ],
        ]],
        [ 'code' => "CAT_1024", 'name' => 'Home Theatre Cables & Accessories' ],
        [ 'code' => "CAT_10551", 'name' => 'Home Theatre Receivers' ],
        [ 'code' => "CAT_1026", 'name' => 'Home Theatre Systems' ],
        [ 'code' => "CAT_29777", 'name' => 'Internet Protocol TV (IPTV)' ],
        [ 'code' => "CAT_642432", 'name' => 'Media Streamers & Players' ],
        [ 'code' => "CAT_32881", 'name' => 'Projector Screens' ],
        [ 'code' => "CAT_2001", 'name' => 'Satellite TV' ],
        [ 'code' => "CAT_10015", 'name' => 'Speaker Stands and Mounts' ],
        [ 'code' => "CAT_10573", 'name' => 'Stereo Receivers' ],
        [ 'code' => "CAT_29879", 'name' => 'Televisions' ],
        [ 'code' => "CAT_908115", 'name' => 'Turntables' ],
        [ 'code' => "CAT_32077", 'name' => 'TV Stands - Category Branch', 'children' => [
            [ 'code' => "CAT_31988", 'name' => 'Fireplace TV Stands' ],
            [ 'code' => "CAT_315836", 'name' => 'TV Stands' ],
        ]],
        [ 'code' => "CAT_26355", 'name' => 'Wall Mounts' ],
        [ 'code' => "CAT_22953", 'name' => 'Wireless Audio Systems' ],
    ]],

    [ 'code' => "CAT_19", 'name' => 'iPod & Portable Audio', 'children' => [
        [ 'code' => "CAT_22793", 'name' => 'Apple iPod & MP3 Cases' ],
        [ 'code' => "CAT_10546", 'name' => 'CD Players' ],
        [ 'code' => "CAT_23274", 'name' => 'Headphones & Headsets - Category Branch', 'children' => [
            [ 'code' => "CAT_36986", 'name' => 'Gaming Console Headsets' ],
            [ 'code' => "CAT_321023", 'name' => 'Headphones & Headsets' ],
        ]],
        [ 'code' => "CAT_26435", 'name' => 'iPods & Portable Media Players' ],
        [ 'code' => "CAT_10086", 'name' => 'MP3 CD Players' ],
        [ 'code' => "CAT_660973", 'name' => 'Other Portable Audio & Accessories' ],
        [ 'code' => "CAT_10088", 'name' => 'Portable Radios' ],
        [ 'code' => "CAT_26995", 'name' => 'Portable, Wireless & Compact Speaker Systems' ],
    ]],

    [ 'code' => "CAT_13", 'name' => 'Movies' ],
    [ 'code' => "CAT_22", 'name' => 'Multi-Dept and Generic', 'children' => [
        [ 'code' => "CAT_7671", 'name' => 'Cables & Adapters' ],
        [ 'code' => "CAT_37740", 'name' => 'Generic' ],
        [ 'code' => "CAT_37789", 'name' => 'Multibox-Other' ],
    ]],

    [ 'code' => "CAT_16", 'name' => 'Music' ],
    [ 'code' => "CAT_27237", 'name' => 'Musical Instruments', 'children' => [
        [ 'code' => "CAT_35716", 'name' => 'Acoustic Guitars' ],
        [ 'code' => "CAT_28512", 'name' => 'Condenser Mics' ],
        [ 'code' => "CAT_27256", 'name' => 'Drum Kits' ],
        [ 'code' => "CAT_27238", 'name' => 'Electric Guitars' ],
        [ 'code' => "CAT_27273", 'name' => 'Guitar Combo Amps & Amp Heads' ],
        [ 'code' => "CAT_28757", 'name' => 'Guitar Pedals' ],
        [ 'code' => "CAT_971511", 'name' => 'Guitar Stings' ],
        [ 'code' => "CAT_27244", 'name' => 'Karaoke' ],
        [ 'code' => "CAT_27239", 'name' => 'Keyboards' ],
        [ 'code' => "CAT_27278", 'name' => 'Mixers & Processors' ],
        [ 'code' => "CAT_27279", 'name' => 'Monitors, Stage Speakers & PA Packages' ],
        [ 'code' => "CAT_35853", 'name' => 'Musical Instrument Accessories' ],
        [ 'code' => "CAT_34824", 'name' => 'Musical Instrument Bags' ],
        [ 'code' => "CAT_660996", 'name' => 'Other Musical Instruments' ],
        [ 'code' => "CAT_27336", 'name' => 'Recording Software' ],
        [ 'code' => "CAT_27246", 'name' => 'Sheet Music' ],
        [ 'code' => "CAT_33552", 'name' => 'Wind Instruments' ],
    ]],

    [ 'code' => "CAT_31177", 'name' => 'Office Supplies', 'children' => [
        [ 'code' => "CAT_10566", 'name' => 'Answering Machines' ],
        [ 'code' => "CAT_1021", 'name' => 'Batteries' ],
        [ 'code' => "CAT_35721", 'name' => 'Binders' ],
        [ 'code' => "CAT_31117", 'name' => 'Binding Machines' ],
        [ 'code' => "CAT_34808", 'name' => 'Boards, Wall Calendars & Deskpads' ],
        [ 'code' => "CAT_1111", 'name' => 'Calculators' ],
        [ 'code' => "CAT_35722", 'name' => 'Clipboards' ],
        [ 'code' => "CAT_26575", 'name' => 'Corded Phones' ],
        [ 'code' => "CAT_24734", 'name' => 'DECT Cordless Phones' ],
        [ 'code' => "CAT_10089", 'name' => 'Digital Voice Recorders' ],
        [ 'code' => "CAT_34809", 'name' => 'Envelopes' ],
        [ 'code' => "CAT_33541", 'name' => 'Filing & Storage' ],
        [ 'code' => "CAT_35723", 'name' => 'Glue & Adhesives' ],
        [ 'code' => "CAT_31127", 'name' => 'Label Makers' ],
        [ 'code' => "CAT_14444", 'name' => 'Labels & Tags' ],
        [ 'code' => "CAT_31120", 'name' => 'Laminators' ],
        [ 'code' => "CAT_31197", 'name' => 'More Office Supplies' ],
        [ 'code' => "CAT_35713", 'name' => 'Notebooks & Notepads' ],
        [ 'code' => "CAT_7673", 'name' => 'Paper' ],
        [ 'code' => "CAT_32516", 'name' => 'Paper Cutters & Trimmers' ],
        [ 'code' => "CAT_37817", 'name' => 'Planners & Refills' ],
        [ 'code' => "CAT_37134", 'name' => 'Report Covers' ],
        [ 'code' => "CAT_37133", 'name' => 'Sheet Protectors' ],
        [ 'code' => "CAT_32868", 'name' => 'Shredder Accessories' ],
        [ 'code' => "CAT_2903", 'name' => 'Shredders' ],
        [ 'code' => "CAT_37820", 'name' => 'Tape' ],
        [ 'code' => "CAT_23013", 'name' => 'VoIP & Internet Phone' ],
        [ 'code' => "CAT_34816", 'name' => 'Writing Instruments' ],
    ]],

    [ 'code' => "CAT_660285", 'name' => 'Pets', 'children' => [
        [ 'code' => "CAT_35590", 'name' => 'Pet Apparel' ],
        [ 'code' => "CAT_35711", 'name' => 'Pet Aquarium & Terrarium Acc.' ],
        [ 'code' => "CAT_35710", 'name' => 'Pet Aquaruims & Terrariums' ],
        [ 'code' => "CAT_35708", 'name' => 'Pet Bedding' ],
        [ 'code' => "CAT_35717", 'name' => 'Pet Books' ],
        [ 'code' => "CAT_27384", 'name' => 'Pet Care-Other' ],
        [ 'code' => "CAT_35592", 'name' => 'Pet Carriers' ],
        [ 'code' => "CAT_35706", 'name' => 'Pet Feeders & Water Containers' ],
        [ 'code' => "CAT_35707", 'name' => 'Pet Furniture' ],
        [ 'code' => "CAT_34825", 'name' => 'Pet Leashes, Collars, Harnesses' ],
        [ 'code' => "CAT_35595", 'name' => 'Pet Skin & Coat Care' ],
        [ 'code' => "CAT_35591", 'name' => 'Pet Treats & Supplements' ],
        [ 'code' => "CAT_35732", 'name' => 'Pet Waste Bags' ],
    ]],

    [ 'code' => "CAT_27603", 'name' => 'Tools & Garden', 'children' => [
        [ 'code' => "CAT_32085", 'name' => 'Flashlights & Lanterns' ],
        [ 'code' => "CAT_31941", 'name' => 'Hand Tools - Category Branch', 'children' => [
            [ 'code' => "CAT_31979", 'name' => 'Chisels, Bolsters & Files' ],
            [ 'code' => "CAT_31983", 'name' => 'Clamps & Vises' ],
            [ 'code' => "CAT_31978", 'name' => 'Drivers & Screwdrivers' ],
            [ 'code' => "CAT_31985", 'name' => 'Hammers & Mallets' ],
            [ 'code' => "CAT_31952", 'name' => 'Hand Planes' ],
            [ 'code' => "CAT_31980", 'name' => 'Hand Saws' ],
            [ 'code' => "CAT_314953", 'name' => 'Hand Tools' ],
            [ 'code' => "CAT_31981", 'name' => 'Levels' ],
            [ 'code' => "CAT_31987", 'name' => 'Mitre Boxes' ],
            [ 'code' => "CAT_32044", 'name' => 'Other Hand Tools' ],
            [ 'code' => "CAT_31984", 'name' => 'Pliers & Wire Cutters' ],
            [ 'code' => "CAT_31982", 'name' => 'Stand Vises' ],
            [ 'code' => "CAT_31948", 'name' => 'Utility Knives & Multi-Tools' ],
            [ 'code' => "CAT_31986", 'name' => 'Wrenches' ],
        ]],
        [ 'code' => "CAT_661015", 'name' => 'Other Tools & Garden Products' ],
        [ 'code' => "CAT_32514", 'name' => 'Power Tool Accessories - Category Branch', 'children' => [
            [ 'code' => "CAT_32836", 'name' => 'Drill Bit Sets' ],
            [ 'code' => "CAT_32835", 'name' => 'Drill Bits' ],
            [ 'code' => "CAT_314955", 'name' => 'Power Tool Accessories' ],
        ]],
        [ 'code' => "CAT_31939", 'name' => 'Power Tools - Category Branch', 'children' => [
            [ 'code' => "CAT_31970", 'name' => 'Air Compressors' ],
            [ 'code' => "CAT_31961", 'name' => 'Biscuit Joiners' ],
            [ 'code' => "CAT_31963", 'name' => 'Disc Grinders' ],
            [ 'code' => "CAT_31958", 'name' => 'Electric Drills' ],
            [ 'code' => "CAT_31959", 'name' => 'Electric Saws' ],
            [ 'code' => "CAT_31966", 'name' => 'Hand Planers' ],
            [ 'code' => "CAT_31967", 'name' => 'Handheld Sanders & Polishers' ],
            [ 'code' => "CAT_31960", 'name' => 'Heat Guns' ],
            [ 'code' => "CAT_31964", 'name' => 'Impact Wrenches' ],
            [ 'code' => "CAT_31962", 'name' => 'Leaf Blowers' ],
            [ 'code' => "CAT_31973", 'name' => 'Other Power Tools' ],
            [ 'code' => "CAT_31969", 'name' => 'Pneumatic Nailers' ],
            [ 'code' => "CAT_31968", 'name' => 'Pneumatic Staplers' ],
            [ 'code' => "CAT_33608", 'name' => 'Pressure Washers' ],
            [ 'code' => "CAT_31971", 'name' => 'Routers & Laminate Trimmers' ],
            [ 'code' => "CAT_31965", 'name' => 'Shop Vacuums' ],
            [ 'code' => "CAT_31972", 'name' => 'Stands and Workstations' ],
        ]],
        [ 'code' => "CAT_35593", 'name' => 'Snow Blowers' ],
        [ 'code' => "CAT_28839", 'name' => 'Workwear & Apparel - Category Branch', 'children' => [
            [ 'code' => "CAT_35589", 'name' => 'Footwear' ],
            [ 'code' => "CAT_31325", 'name' => 'Gloves' ],
            [ 'code' => "CAT_31324", 'name' => 'Headwear' ],
            [ 'code' => "CAT_31329", 'name' => 'Jackets, Vests & Tops' ],
            [ 'code' => "CAT_10737", 'name' => 'Pants & Shorts' ],
            [ 'code' => "CAT_10738", 'name' => 'Socks' ],
            [ 'code' => "CAT_28841", 'name' => 'T-Shirts' ],
            [ 'code' => "CAT_314963", 'name' => 'Workwear & Apparel' ],
        ]],
    ]],

    [ 'code' => "CAT_26337", 'name' => 'Toys, Sports & Recreation', 'children' => [
        [ 'code' => "CAT_659225", 'name' => 'Sports & Recreation', 'children' => [
            [ 'code' => "CAT_35588", 'name' => 'Bikes & Trikes - Category Branch', 'children' => [
                [ 'code' => "CAT_328644", 'name' => 'Bikes & Trikes' ],
                [ 'code' => "CAT_37191", 'name' => 'Electric Bikes' ],
                [ 'code' => "CAT_35668", 'name' => 'Toys- Kids Bikes & Trikes' ],
            ]],
            [ 'code' => "CAT_29041", 'name' => 'Binoculars & Monoculars' ],
            [ 'code' => "CAT_31091", 'name' => 'Breathalyzers' ],
            [ 'code' => "CAT_32808", 'name' => 'Camping Stoves' ],
            [ 'code' => "CAT_33631", 'name' => 'Coolers' ],
            [ 'code' => "CAT_37327", 'name' => 'Crossbow Accessories' ],
            [ 'code' => "CAT_37326", 'name' => 'Crossbow Bolts' ],
            [ 'code' => "CAT_35688", 'name' => 'Crossbows' ],
            [ 'code' => "CAT_25033", 'name' => 'Hammocks' ],
            [ 'code' => "CAT_37206", 'name' => 'Head Lamps' ],
            [ 'code' => "CAT_23553", 'name' => 'Knives & Blades' ],
            [ 'code' => "CAT_10007", 'name' => 'Metal Detectors' ],
            [ 'code' => "CAT_32843", 'name' => 'Microscopes' ],
            [ 'code' => "CAT_31954", 'name' => 'More Camping Accessories' ],
            [ 'code' => "CAT_35728", 'name' => 'More Sports & Recreation' ],
            [ 'code' => "CAT_659860", 'name' => 'Outdoor Recreational Games' ],
            [ 'code' => "CAT_659896", 'name' => 'Rec Room Games', 'children' => [
                [ 'code' => "CAT_329705", 'name' => 'Air Hockey Tables' ],
                [ 'code' => "CAT_37334", 'name' => 'Dart Boards' ],
                [ 'code' => "CAT_37333", 'name' => 'Foosball Tables' ],
                [ 'code' => "CAT_36029", 'name' => 'Game Tables' ],
                [ 'code' => "CAT_659900", 'name' => 'Rec Room Game Equipment' ],
                [ 'code' => "CAT_37332", 'name' => 'Table Tennis' ],
            ]],
            [ 'code' => "CAT_35584", 'name' => 'Scooters' ],
            [ 'code' => "CAT_31953", 'name' => 'Sleeping Bags' ],
            [ 'code' => "CAT_34837", 'name' => 'Solar Panel & Power Pack Accessories' ],
            [ 'code' => "CAT_33157", 'name' => 'Solar Panels & Power Packs' ],
            [ 'code' => "CAT_32724", 'name' => 'Sports & Beach Umbrellas' ],
            [ 'code' => "CAT_31998", 'name' => 'Sports Impact Protection' ],
            [ 'code' => "CAT_32880", 'name' => 'Sports Memorabilia' ],
            [ 'code' => "CAT_31992", 'name' => 'Tarps' ],
            [ 'code' => "CAT_32844", 'name' => 'Telescopes' ],
            [ 'code' => "CAT_26379", 'name' => 'Tents, Shelters & Screen Rooms' ],
            [ 'code' => "CAT_33530", 'name' => 'Two-way Radios' ],
        ]],
        [ 'code' => "CAT_659219", 'name' => 'Toys, Games & Collectibles', 'children' => [
            [ 'code' => "CAT_32082", 'name' => 'Action Figures, Dolls & Robots' ],
            [ 'code' => "CAT_938334", 'name' => 'Anatomical and Science Models' ],
            [ 'code' => "CAT_32879", 'name' => 'Board Games & Card Games' ],
            [ 'code' => "CAT_32084", 'name' => 'Building Blocks & Sets' ],
            [ 'code' => "CAT_32010", 'name' => 'Collectable Models & Replicas' ],
            [ 'code' => "CAT_619653", 'name' => 'Drone Parts & Accessories' ],
            [ 'code' => "CAT_616514", 'name' => 'Drones' ],
            [ 'code' => "CAT_35583", 'name' => 'Electronic Learning Toys' ],
            [ 'code' => "CAT_34819", 'name' => 'Model Kits' ],
            [ 'code' => "CAT_34820", 'name' => 'Model Rockets & Accessories' ],
            [ 'code' => "CAT_24913", 'name' => 'Other Toys & Gadgets' ],
            [ 'code' => "CAT_33184", 'name' => 'Puzzles' ],
            [ 'code' => "CAT_32864", 'name' => 'RC Parts & Accessories' ],
            [ 'code' => "CAT_32081", 'name' => 'Remote Control Toys' ],
            [ 'code' => "CAT_35582", 'name' => 'Toys-Ride On Toys & Go Karts - Category Branch', 'children' => [
                [ 'code' => "CAT_35669", 'name' => 'Go Karts' ],
                [ 'code' => "CAT_35780", 'name' => 'Ride On Toys' ],
            ]],
        ]],
        [ 'code' => "CAT_33176", 'name' => 'Wall Decals & Graphics' ],
    ]],

    [ 'code' => "CAT_654823", 'name' => 'Wearable Technology', 'children' => [
        [ 'code' => "CAT_654825", 'name' => 'Generic Smart Wearables' ],
        [ 'code' => "CAT_27405", 'name' => 'GPS Tracking' ],
        [ 'code' => "CAT_32774", 'name' => 'GPS Watches & Running GPS' ],
        [ 'code' => "CAT_654827", 'name' => 'Smart Clothing - Pants & Bottoms' ],
        [ 'code' => "CAT_654826", 'name' => 'Smart Clothing - Tops, Shirts & Jackets' ],
        [ 'code' => "CAT_654990", 'name' => 'Smart Healthcare Devices' ],
        [ 'code' => "CAT_654998", 'name' => 'Smart Pet Devices' ],
        [ 'code' => "CAT_35587", 'name' => 'Smartwatches, Fitness Trackers' ],
        [ 'code' => "CAT_28578", 'name' => 'Sports Performance Monitors' ],
        [ 'code' => "CAT_1170746", 'name' => 'Virtual Reality Headsets' ],
        [ 'code' => "CAT_33554", 'name' => 'Wearable Technology Accessories' ],
    ]],
];

function printCate($parent, $cate)
{
    echo $cate['code'], "\t";

    if ($parent) {
        echo $parent['code'], "\t";
    }

    echo $cate['name'], "\n";

    if (isset($cate['children'])) {
        foreach ($cate['children'] as $child) {
            printCate($cate, $child);
        }
    }
}

function saveCate($parent, $cate, $desc)
{
    $id = $cate['code'];
    $name = $cate['name'];

    array_push($desc, $name);

    $parentId = '';
    if ($parent) {
        $parentId = $parent['code'];
    }

    $di = \Phalcon\Di::getDefault();
    $db = $di->get('db');

    $db->insertAsDict('bestbuy_category', [
        'category_id'   => $id,
        'category_name' => $name,
        'parent_id'     => $parentId,
        'category_desc' => implode(' > ', $desc)
    ]);

    if (isset($cate['children'])) {
        foreach ($cate['children'] as $child) {
            saveCate($cate, $child, $desc);
        }
    }
}

include '../../public/init.php';

foreach ($bestbuyCate as $cate) {
#   printCate(null, $cate);
    saveCate(null, $cate, []);
}
