USE bte;

-- INSERT INTO bte_order_seq VALUES ()

CREATE TABLE IF NOT EXISTS `bte_order_seq` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;
