USE bte;

ALTER TABLE `amazon_order`
	ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`),
	ADD UNIQUE INDEX `OrderId` (`OrderId`);

ALTER TABLE `amazon_order_item`
	ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`),
	ADD INDEX `OrderId` (`OrderId`);

ALTER TABLE `amazon_order_shipping_address`
	ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`),
	ADD UNIQUE INDEX `OrderId` (`OrderId`);
