USE bte;

CREATE TABLE IF NOT EXISTS `shopping_cart` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`order_id` VARCHAR(40) NOT NULL,
	`sku` VARCHAR(40) NOT NULL,
	`qty` INT(11) NOT NULL,
	`branch_name` VARCHAR(40) NULL DEFAULT NULL,
	`branch_code` VARCHAR(10) NULL DEFAULT NULL,
	`createdon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX `order_id` (`order_id`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;
