USE bte;

CREATE TABLE IF NOT EXISTS `dropship_tracking` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`orderid` VARCHAR(40) NOT NULL,
	`shipdate` DATE NOT NULL,
	`carrier` VARCHAR(40) NOT NULL,
	`service` VARCHAR(40) NOT NULL DEFAULT '',
	`trackingnum` VARCHAR(40) NOT NULL,
	`uploaded` TINYINT(4) NOT NULL DEFAULT '0',
	`createdon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `orderid` (`orderid`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;
