USE bte;

CREATE TABLE IF NOT EXISTS `rakuten_order_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SellerShopperNumber` varchar(20) NOT NULL,
  `Receipt_ID` varchar(20) NOT NULL COMMENT 'Order ID',
  `Receipt_Item_ID` varchar(20) NOT NULL,
  `ListingID` varchar(20) NOT NULL,
  `Date_Entered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Sku` varchar(40) NOT NULL,
  `ReferenceId` varchar(40) NOT NULL,
  `Quantity` int(11) NOT NULL,
  `Qty_Shipped` int(11) NOT NULL,
  `Qty_Cancelled` int(11) NOT NULL,
  `Title` varchar(200) NOT NULL,
  `Price` float(10,2) NOT NULL,
  `Product_Rev` float(10,2) NOT NULL,
  `Shipping_Cost` float(10,2) NOT NULL,
  `ProductOwed` float(10,2) NOT NULL,
  `ShippingOwed` float(10,2) NOT NULL,
  `Commission` float(10,2) NOT NULL,
  `ShippingFee` float(10,2) NOT NULL,
  `PerItemFee` float(10,2) NOT NULL,
  `Tax_Cost` float(10,2) NOT NULL,
  `Bill_To_Company` varchar(40) NOT NULL,
  `Bill_To_Phone` varchar(20) NOT NULL,
  `Bill_To_Fname` varchar(20) NOT NULL,
  `Bill_To_Lname` varchar(20) NOT NULL,
  `Email` varchar(80) NOT NULL,
  `Ship_To_Name` varchar(40) NOT NULL,
  `Ship_To_Company` varchar(40) NOT NULL,
  `Ship_To_Street1` varchar(40) NOT NULL,
  `Ship_To_Street2` varchar(40) NOT NULL,
  `Ship_To_City` varchar(20) NOT NULL,
  `Ship_To_State` varchar(20) NOT NULL,
  `Ship_To_Zip` varchar(10) NOT NULL,
  `ShippingMethodId` varchar(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Receipt_ID` (`Receipt_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
