USE bte;

CREATE TABLE IF NOT EXISTS `newegg_order_report` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Filename` varchar(40) NOT NULL,
  `OrderNumber` varchar(40) NOT NULL,
  `OrderDateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SalesChannel` varchar(10) NOT NULL,
  `FulfillmentOption` varchar(20) NOT NULL,
  `ShipToAddressLine1` varchar(80) NOT NULL,
  `ShipToAddressLine2` varchar(80) NOT NULL,
  `ShipToCity` varchar(20) NOT NULL,
  `ShipToState` varchar(20) NOT NULL,
  `ShipToZipCode` varchar(10) NOT NULL,
  `ShipToCountry` varchar(20) NOT NULL,
  `ShipToFirstName` varchar(20) NOT NULL,
  `ShipToLastName` varchar(20) NOT NULL,
  `ShipToCompany` varchar(40) NOT NULL,
  `ShipToPhoneNumber` varchar(20) NOT NULL,
  `OrderCustomerEmail` varchar(80) NOT NULL,
  `OrderShippingMethod` varchar(40) NOT NULL,
  `ItemSellerPartNo` varchar(40) NOT NULL,
  `ItemNeweggNo` varchar(40) NOT NULL,
  `ItemUnitPrice` float(10,2) NOT NULL,
  `ExtendUnitPrice` float(10,2) NOT NULL,
  `ItemUnitShippingCharge` float(10,2) NOT NULL,
  `ExtendShippingCharge` float(10,2) NOT NULL,
  `OrderShippingTotal` float(10,2) NOT NULL,
  `GSTorHSTTotal` float(10,2) NOT NULL,
  `PSTorQSTTotal` float(10,2) NOT NULL,
  `OrderTotal` float(10,2) NOT NULL,
  `QuantityOrdered` int(11) NOT NULL,
  `QuantityShipped` int(11) NOT NULL,
  `ShipDate` date NOT NULL,
  `ActualShippingCarrier` varchar(40) NOT NULL,
  `ActualShippingMethod` varchar(40) NOT NULL,
  `TrackingNumber` varchar(40) NOT NULL,
  `ShipFromAddress` varchar(80) NOT NULL,
  `ShipFromCity` varchar(20) NOT NULL,
  `ShipFromState` varchar(20) NOT NULL,
  `ShipFromZipcode` varchar(10) NOT NULL,
  `ShipFromName` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `OrderNumber` (`OrderNumber`),
  KEY `Filename` (`Filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
