USE bte;

-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.16-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table bte.keyword_brand
CREATE TABLE IF NOT EXISTS `keyword_brand` (
  `keyword` varchar(40) NOT NULL,
  `brand` varchar(40) NOT NULL,
  PRIMARY KEY (`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table bte.keyword_brand: ~0 rows (approximately)
/*!40000 ALTER TABLE `keyword_brand` DISABLE KEYS */;
INSERT INTO `keyword_brand` (`keyword`, `brand`) VALUES
	('3M ', '3M '),
	('A-DATA Technology', 'A-DATA Technology'),
	('Acer', 'Acer'),
	('AcomData', 'AcomData'),
	('Adaptec', 'Adaptec'),
	('ADATA', 'ADATA'),
	('ADESSO NUSCAN', 'ADESSO NUSCAN'),
	('AMETA', 'AMETA'),
	('Antec', 'Antec'),
	('APC ', 'APC '),
	('APEVIA', 'APEVIA'),
	('Arozzi', 'Arozzi'),
	('ARUBA', 'ARUBA'),
	('ASROCK', 'ASROCK'),
	('ASUS', 'ASUS'),
	('AT&T', 'AT&T'),
	('AVERMEDIA', 'AVERMEDIA'),
	('Azio ', 'Azio '),
	('BELKIN', 'BELKIN'),
	('BenQ', 'BenQ'),
	('Bentley', 'Bentley'),
	('BlackBerry', 'BlackBerry'),
	('Brother', 'Brother'),
	('BUFFALO', 'BUFFALO'),
	('Buffalo Technology', 'Buffalo Technology'),
	('C2G', 'C2G'),
	('CAMPUS', 'CAMPUS'),
	('CANON', 'CANON'),
	('Casio', 'Casio'),
	('Cisco', 'Cisco'),
	('CONAIR', 'CONAIR'),
	('Cooler Master', 'Cooler Master'),
	('Corsair', 'Corsair'),
	('Creative', 'Creative'),
	('Crucial', 'Crucial'),
	('CUISINART', 'CUISINART'),
	('CYBERPOWER', 'CYBERPOWER'),
	('D-Link', 'D-Link'),
	('DELL', 'DELL'),
	('Dolica', 'Dolica'),
	('DriveSmart', 'DriveSmart'),
	('Edimax', 'Edimax'),
	('EliteDesk', 'HP'),
	('ENERMAX', 'ENERMAX'),
	('Epson', 'Epson'),
	('Eyefi', 'Eyefi'),
	('FUJI', 'FUJI'),
	('FUJITSU', 'FUJITSU'),
	('Garmin', 'Garmin'),
	('Genicom', 'Genicom'),
	('GIGA ', 'GIGABYTE'),
	('GIGA-BYTE', 'GIGABYTE'),
	('Gigabyte', 'Gigabyte'),
	('Hawking Technolgoies', 'Hawking Technolgoies'),
	('Hewlett Packard', 'Hewlett Packard'),
	('Hisense', 'Hisense'),
	('HP ', 'HP '),
	('iEssentials', 'iEssentials'),
	('Intel', 'Intel'),
	('IOGEAR', 'IOGEAR'),
	('IOMEGA', 'IOMEGA'),
	('ioSafe', 'ioSafe'),
	('JETWAY', 'JETWAY'),
	('JUNIPER', 'JUNIPER'),
	('Kensington', 'Kensington'),
	('Keytronic', 'Keytronic'),
	('KINGSTON', 'KINGSTON'),
	('KONICA', 'KONICA'),
	('LaCie', 'LaCie'),
	('Lenovo', 'Lenovo'),
	('Lexar', 'Lexar'),
	('LG ', 'LG '),
	('LightStream', 'LightStream'),
	('LINKSYS', 'LINKSYS'),
	('Logitech', 'Logitech'),
	('MAD CATZ', 'MAD CATZ'),
	('MARUSON', 'MARUSON'),
	('Matias', 'Matias'),
	('MATROX', 'MATROX'),
	('MAXELL', 'MAXELL'),
	('MCAFEE', 'MCAFEE'),
	('Mediasonic', 'Mediasonic'),
	('MEElectronics', 'MEElectronics'),
	('MEGABRAND', 'MEGABRAND'),
	('Microline', 'Microline'),
	('Monster', 'Monster'),
	('MOTO ', 'MOTO '),
	('MSI', 'MSI'),
	('MultiSync', 'MultiSync'),
	('NETGEAR', 'NETGEAR'),
	('Noctua', 'Noctua'),
	('NoteBook TP', 'Lenovo'),
	('NVIDIA', 'NVIDIA'),
	('OKI', 'OKI'),
	('OLYMPUS', 'OLYMPUS'),
	('Optiplex', 'Optiplex'),
	('PANASONIC', 'PANASONIC'),
	('PAPAGO', 'PAPAGO'),
	('PISEN', 'PISEN'),
	('PIXMA', 'Canon'),
	('Plantronics', 'Plantronics'),
	('ProSafe', 'ProSafe'),
	('Quantum', 'Quantum'),
	('Radeon', 'Radeon'),
	('Ricoh', 'Ricoh'),
	('RIDATA', 'RIDATA'),
	('Samsung', 'Samsung'),
	('SanDisk', 'SanDisk'),
	('Sapphire', 'Sapphire'),
	('ScanSnap', 'ScanSnap'),
	('Seagate', 'Seagate'),
	('Seasonic', 'Seasonic'),
	('SecurLink', 'SecurLink'),
	('SHARP', 'SHARP'),
	('SmartRack', 'SmartRack'),
	('Smartti', 'Smartti'),
	('SNAGLESS', 'SNAGLESS'),
	('SOLIDTEK', 'SOLIDTEK'),
	('SonicWALL', 'SonicWALL'),
	('Sony', 'Sony'),
	('StarTech.com', 'StarTech.com'),
	('SteelSeries', 'SteelSeries'),
	('StyleView', 'StyleView'),
	('Supermicro', 'Supermicro'),
	('Survivor', 'Survivor'),
	('Swingline', 'Swingline'),
	('Swiss Gear', 'Swiss Gear'),
	('Swordfish Tech', 'Swordfish Tech'),
	('Synology', 'Synology'),
	('TallyGenicom', 'TallyGenicom'),
	('Targus', 'Targus'),
	('Tenda Technology', 'Tenda Technology'),
	('Thermal', 'Thermal'),
	('Thermaltake', 'Thermaltake'),
	('ThinkCentre', 'Lenovo'),
	('ThinkPad', 'Lenovo'),
	('ThinkServer', 'Lenovo'),
	('ThinkStation', 'Lenovo'),
	('TIGER', 'TIGER'),
	('TIZO', 'TIZO'),
	('Toshiba', 'Toshiba'),
	('TP-LINK', 'TP-LINK'),
	('TRENDnet', 'TRENDnet'),
	('Tripp Lite', 'Tripp Lite'),
	('Ubiquiti', 'Ubiquiti'),
	('Unitech', 'Unitech'),
	('Universal', 'Universal'),
	('Vantec', 'Vantec'),
	('Verbatim', 'Verbatim'),
	('VERTAGEAR', 'VERTAGEAR'),
	('ViewSonic', 'ViewSonic'),
	('VISIONTEK', 'VISIONTEK'),
	('VitaSound', 'VitaSound'),
	('WatchGuard', 'WatchGuard'),
	('WD ', 'WD '),
	('Web Smart', 'Web Smart'),
	('WebSmart', 'WebSmart'),
	('Western Digital', 'Western Digital'),
	('WIREMOLD', 'WIREMOLD'),
	('WorkFit', 'WorkFit'),
	('Xerox', 'Xerox'),
	('xStack', 'xStack'),
	('ZALMAN', 'ZALMAN'),
	('zBoost', 'zBoost'),
	('ZBOX', 'ZOTAC'),
	('ZOJIRUSHI', 'ZOJIRUSHI'),
	('ZOTAC ', 'ZOTAC '),
	('ZTE', 'ZTE'),
	('ZWILLING', 'ZWILLING');
/*!40000 ALTER TABLE `keyword_brand` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
