USE bte;

CREATE TABLE IF NOT EXISTS `overstock_log` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`sku` VARCHAR(40) NOT NULL,
	`condition` VARCHAR(20) NOT NULL,
	`cost` VARCHAR(20) NOT NULL,
	`qty` INT(11) NOT NULL,
	`title` VARCHAR(120) NOT NULL,
	`allocation` VARCHAR(20) NOT NULL,
	`mpn` VARCHAR(40) NOT NULL,
	`upc` VARCHAR(20) NOT NULL,
	`weight` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
